import { Suspense } from "react";
import { Bird, CheckCircle2, LoaderCircle } from "lucide-react";
import Link from "next/link";
import AuthForm from "@/components/auth-form";

export default function CadastroPage() {
  return <main className="min-h-screen bg-[#07101f] text-white lg:grid lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden border-r border-white/[.07] p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 [background-image:radial-gradient(circle_at_20%_15%,rgba(16,185,129,.19),transparent_35%),radial-gradient(circle_at_80%_85%,rgba(245,158,11,.12),transparent_30%)]"/><Link href="/" className="relative flex items-center gap-3 text-white no-underline"><span className="grid size-11 place-items-center rounded-2xl bg-emerald-400 text-slate-950"><Bird size={23}/></span><span><strong className="block">Nutri Pombos</strong><small className="text-[9px] font-bold uppercase tracking-[.2em] text-emerald-400">Columbofilia inteligente</small></span></Link><div className="relative max-w-xl"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-300">Comece hoje</p><h1 className="mt-4 text-6xl font-semibold leading-[.95] tracking-[-.06em]">7 dias para<br/><span className="text-emerald-300">conhecer tudo.</span></h1><div className="mt-10 space-y-4">{["Teste completo sem cartão de crédito","Mais de 30 ferramentas profissionais","Cancele sem compromisso"].map(v=><div key={v} className="flex items-center gap-3 text-sm text-slate-400"><CheckCircle2 size={17} className="text-emerald-400"/>{v}</div>)}</div></div><p className="relative text-[10px] text-slate-600">Nutri Pombos • Tecnologia para o seu pombal</p></section>
    <section className="flex min-h-screen items-center justify-center px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center gap-3 text-white no-underline lg:hidden"><span className="grid size-10 place-items-center rounded-xl bg-emerald-400 text-slate-950"><Bird size={20}/></span><b>Nutri Pombos</b></Link><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-amber-300">Teste grátis por 7 dias</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.045em]">Crie sua conta</h2><p className="mt-3 text-sm leading-6 text-slate-500">Tenha acesso ao sistema completo e organize sua próxima temporada.</p><Suspense fallback={<div className="mt-8 flex items-center justify-center py-8"><LoaderCircle size={20} className="animate-spin text-slate-500"/></div>}><AuthForm mode="cadastro"/></Suspense><p className="mt-7 text-center text-[10px] leading-5 text-slate-600">Ao criar uma conta, você concorda com os termos de uso e política de privacidade.</p></div></section>
  </main>;
}
