"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { T } from "../theme";

type Pombo={id:number;nome:string|null;anilha:string;sexo:string};
type Casal={id:string;machoId:string;femeaId:string;tipo:string;separacao:string;reencontro:string;obs:string};
type Form=Omit<Casal,"id">;
const KEY="nutripombos-viuvez-v1",CHECK_KEY="nutripombos-viuvez-check-v1";
const CHECKLIST=["Separar o casal conforme o manejo escolhido","Observar comportamento e sinais de estresse","Ajustar alimentação conforme categoria e condição","Planejar sessão leve ou descanso antes do enceste","Apresentação breve e supervisionada, se utilizada","Encestamento calmo e seguro","Reencontro supervisionado após o retorno"];
const hoje=()=>new Date().toISOString().slice(0,10),futuro=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,10);
const vazio=():Form=>({machoId:"",femeaId:"",tipo:"Clássica",separacao:hoje(),reencontro:futuro(),obs:""});
function read<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
function diff(a:string,b:string){return Math.ceil((new Date(`${b}T12:00:00`).getTime()-new Date(`${a}T12:00:00`).getTime())/86400000)}

export default function Viuvez(){
  const[pombos,setPombos]=useState<Pombo[]>([]);const[casais,setCasais]=useState<Casal[]>([]);const[feitos,setFeitos]=useState<string[]>([]);const[ready,setReady]=useState(false);const[show,setShow]=useState(false);const[editId,setEditId]=useState<string|null>(null);const[form,setForm]=useState<Form>(vazio());
  useEffect(()=>{setCasais(read(KEY,[]));setFeitos(read(CHECK_KEY,[]));fetch("/api/pombos").then(r=>r.json()).then(v=>setPombos(Array.isArray(v)?v:[])).catch(()=>setPombos([]));setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(casais))},[casais,ready]);useEffect(()=>{if(ready)localStorage.setItem(CHECK_KEY,JSON.stringify(feitos))},[feitos,ready]);
  const normal=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase(),machos=pombos.filter(p=>normal(p.sexo)==="macho"),femeas=pombos.filter(p=>normal(p.sexo)==="femea"),pct=Math.round(feitos.length/CHECKLIST.length*100);
  function abrir(v?:Casal){setForm(v?{machoId:v.machoId,femeaId:v.femeaId,tipo:v.tipo,separacao:v.separacao,reencontro:v.reencontro,obs:v.obs}:vazio());setEditId(v?.id||null);setShow(true)}
  function salvar(){if(!form.machoId||!form.femeaId){alert("Selecione macho e fêmea.");return}if(form.reencontro<form.separacao){alert("O reencontro não pode ser anterior à separação.");return}setCasais(v=>editId?v.map(c=>c.id===editId?{...c,...form}:c):[...v,{id:crypto.randomUUID(),...form}]);setShow(false);setEditId(null)}
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10,marginBottom:18}}><div><h1 style={T.h1}>❤️ Sistema de Viuvez</h1><p style={{...T.small,marginTop:4}}>Controle de casais e ciclos motivacionais</p></div><Link href="/centro-provas" style={{...T.btnGhost,textDecoration:"none"}}>← Centro</Link></div>
    <div style={{padding:"10px 13px",marginBottom:12,borderRadius:9,color:T.blue,background:`${T.blue}12`,border:`1px solid ${T.blue}44`,fontSize:11,lineHeight:1.6}}>ℹ️ Manejo opcional. Observe o comportamento individual, evite privação, excitação excessiva ou separações que causem estresse e priorize o bem-estar das aves.</div>
    <section style={T.card}><div style={{display:"flex",justifyContent:"space-between",marginBottom:9}}><Title>✅ Checklist Semanal</Title><b style={{color:pct===100?T.green:T.gold}}>{feitos.length}/{CHECKLIST.length}</b></div><div style={{height:6,marginBottom:11,borderRadius:4,background:"#ffffff14"}}><div style={{height:"100%",width:`${pct}%`,background:pct===100?T.green:T.gold}}/></div>{CHECKLIST.map((c,i)=>{const id=`check-${i}`,on=feitos.includes(id);return <button key={c} onClick={()=>setFeitos(v=>on?v.filter(x=>x!==id):[...v,id])} style={{width:"100%",display:"flex",gap:9,alignItems:"center",padding:9,marginBottom:4,textAlign:"left",borderRadius:8,color:on?T.green:T.dim,background:on?`${T.green}12`:"#ffffff05",border:`1px solid ${on?T.green:T.border}`}}><span style={{width:21,height:21,display:"grid",placeItems:"center",borderRadius:6,background:on?T.green:"#ffffff12",color:T.bg}}>{on?"✓":""}</span>{c}</button>})}</section>
    <section style={T.card}><Title>📖 Tipos de Manejo</Title>{[["Clássica","Um parceiro separado e apresentação breve antes do enceste."],["Dupla","Ambos competem; exige observação cuidadosa do estresse e recuperação."],["Semi-viuvez","Separação parcial e manejo mais moderado."]].map(([t,d])=><div key={t} style={{padding:"9px 0",borderBottom:`1px solid ${T.border}`}}><b style={{color:T.gold}}>{t}</b><div style={T.small}>{d}</div></div>)}</section>
    <button onClick={()=>abrir()} style={{...T.btn,marginBottom:12}}>+ Novo Casal</button>
    {show&&<section style={T.card}><Title>{editId?"✏️ Editar Casal":"➕ Novo Casal"}</Title><Field label="🐦 Macho"><select value={form.machoId} onChange={e=>setForm(v=>({...v,machoId:e.target.value}))} style={T.input}><option value="">Selecionar macho...</option>{machos.map(p=><option key={p.id} value={p.id}>{p.nome||"Sem nome"} — {p.anilha}</option>)}</select></Field><Field label="🐦 Fêmea"><select value={form.femeaId} onChange={e=>setForm(v=>({...v,femeaId:e.target.value}))} style={T.input}><option value="">Selecionar fêmea...</option>{femeas.map(p=><option key={p.id} value={p.id}>{p.nome||"Sem nome"} — {p.anilha}</option>)}</select></Field><Field label="Tipo"><div style={{display:"flex",gap:6}}>{["Clássica","Dupla","Semi-viuvez"].map(t=><button key={t} onClick={()=>setForm(v=>({...v,tipo:t}))} style={{flex:1,padding:9,borderRadius:8,fontSize:11,color:form.tipo===t?T.bg:T.dim,background:form.tipo===t?T.gold:T.bgInput,border:`1px solid ${form.tipo===t?T.gold:T.border}`}}>{t}</button>)}</div></Field><div className="widow-date-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Field label="📅 Separação"><input type="date" value={form.separacao} onChange={e=>setForm(v=>({...v,separacao:e.target.value}))} style={T.input}/></Field><Field label="💕 Reencontro"><input type="date" value={form.reencontro} onChange={e=>setForm(v=>({...v,reencontro:e.target.value}))} style={T.input}/></Field></div><Field label="📝 Observações"><textarea rows={3} value={form.obs} onChange={e=>setForm(v=>({...v,obs:e.target.value}))} placeholder="Comportamento, adaptação e sinais de estresse..." style={{...T.input,height:80}}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>{setShow(false);setEditId(null)}} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvar} style={{...T.btn,flex:2}}>💾 Salvar</button></div></section>}
    {casais.map(c=>{const macho=pombos.find(p=>String(p.id)===c.machoId),femea=pombos.find(p=>String(p.id)===c.femeaId),ciclo=diff(c.separacao,c.reencontro),restante=diff(hoje(),c.reencontro);return <section key={c.id} style={T.card}><div style={{display:"flex",justifyContent:"space-between",gap:9}}><div><Tag>{c.tipo}</Tag><h3 style={{margin:"7px 0 3px"}}>{macho?.nome||"Macho não encontrado"} <span style={{color:"#F472B6"}}>×</span> {femea?.nome||"Fêmea não encontrada"}</h3>{c.obs&&<div style={{...T.small,fontStyle:"italic"}}>{c.obs}</div>}</div><div style={{display:"flex",gap:5}}><button onClick={()=>abrir(c)} style={T.btnGhost}>✏️</button><button onClick={()=>{if(confirm("Remover casal?"))setCasais(v=>v.filter(x=>x.id!==c.id))}} style={T.btnDanger}>🗑️</button></div></div><div className="widow-stats" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:11}}><Mini label="Separação" value={c.separacao}/><Mini label="Reencontro" value={c.reencontro} color={T.gold}/><Mini label={restante>0?"Faltam":"Ciclo"} value={restante>0?`${restante}d`:`${ciclo}d`} color={restante>0&&restante<=2?T.red:T.gold}/></div></section>})}{ready&&!casais.length&&<div style={{padding:32,textAlign:"center",color:T.dim}}>Nenhum casal cadastrado.</div>}
  </div><style jsx global>{`button,input,select,textarea{font-family:inherit}button{cursor:pointer}select option{background:${T.bgInput}}@media(max-width:520px){.widow-date-grid{grid-template-columns:1fr!important}.widow-stats{grid-template-columns:1fr 1fr 1fr!important}}`}</style></main>
}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold}}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:11}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
function Tag({children}:{children:React.ReactNode}){return <span style={{padding:"2px 7px",borderRadius:20,color:"#F472B6",background:"#f472b618",fontSize:10}}>{children}</span>}
function Mini({label,value,color=T.white}:{label:string;value:string;color?:string}){return <div style={{padding:9,textAlign:"center",borderRadius:8,background:"#ffffff06",border:`1px solid ${T.border}`}}><div style={T.small}>{label}</div><b style={{color,fontSize:12}}>{value}</b></div>}
