"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { loadConfig } from "../config";
import { T } from "../theme";

type Tab="protocolo"|"mistura"|"tecnicas"|"erros"|"sinais";
type Dia={dia:string;emoji:string;titulo:string;cor:string;objetivo:string;itens:string[];alimentacao:string;mix:string;dica:string;destaque?:boolean};
const DIAS:Dia[]=[
  {dia:"Domingo",emoji:"💙",titulo:"Recuperação",cor:"#1E40AF",objetivo:"Recuperação total pós-prova",itens:["Banho opcional em condições adequadas","Água limpa e reposição conforme protocolo","Comida leve e observação do apetite","Repouso sem treino","Avaliar cada ave individualmente"],alimentacao:"Cevada 50% + Trigo 30% + Arroz 20% — referência leve",mix:"2g/pombo — dose reduzida de referência",dica:"Recuperação faz parte do treinamento."},
  {dia:"Segunda",emoji:"🟢",titulo:"Voos Livres Controlados",cor:"#166534",objetivo:"Aeróbico leve e coesão do lote",itens:["Voo livre de acordo com a forma do lote","Observar coesão sem forçar aves cansadas","Encerrar diante de calor, predadores ou esforço excessivo","Registrar duração e comportamento","Hidratação após a sessão"],alimentacao:"Milho 35% + Trigo 30% + Sorgo 20% + Ervilha 15%",mix:"1g/pombo — referência de manutenção",dica:"Coesão é útil, mas bem-estar e recuperação vêm primeiro."},
  {dia:"Terça",emoji:"🔴",titulo:"Soltura Curta",cor:"#7F1D1D",objetivo:"Trabalhar retorno eficiente",itens:["Distância de referência: 20–40km","Priorizar retorno consistente","Pequenos grupos antes de individualizar","Individual somente para aves experientes","Registrar tempo em HH:MM:SS"],alimentacao:"Milho 40% + Trigo 25% + Sorgo 20% + Ervilha 10% + Girassol 5%",mix:"1,5g/pombo — referência pré-esforço",dica:"Individualização deve ser gradual e segura.",destaque:true},
  {dia:"Quarta",emoji:"🟡",titulo:"Treino Aéreo",cor:"#854D0E",objetivo:"Condicionamento sem exaustão",itens:["Duração ajustada à recuperação","Não perseguir ou assustar o lote","Observar respiração e pouso","Evitar vento forte e calor","Interromper diante de fadiga"],alimentacao:"Milho 40% + Trigo 25% + Sorgo 20% + Ervilha 15%",mix:"1g/pombo — suporte de referência",dica:"Qualidade e recuperação valem mais que intensidade forçada."},
  {dia:"Quinta",emoji:"🟣",titulo:"Treino Técnico",cor:"#4C1D95",objetivo:"Orientação progressiva",itens:["Soltura curta de 10–25km","Variar direção gradualmente","Usar pontos seguros e conhecidos pelo tratador","Boa visibilidade obrigatória","Registrar clima e recuperação"],alimentacao:"Milho 45% + Trigo 25% + Sorgo 20% + Ervilha 10%",mix:"1,5g/pombo — conforme protocolo",dica:"Não treine em neblina, tempestade ou condições inseguras."},
  {dia:"Sexta",emoji:"❤️",titulo:"Motivação e Descanso",cor:"#831843",objetivo:"Manter vínculo e reduzir desgaste",itens:["Manejo calmo e previsível","Motivação sem privação ou estresse","Quase nenhum desgaste físico","Verificar condição individual","Não testar produtos ou técnicas novas"],alimentacao:"Milho 50% + Trigo 25% + Sorgo 15% + Ervilha 10%",mix:"1g/pombo — leve",dica:"Motivação deve respeitar comportamento e bem-estar.",destaque:true},
  {dia:"Sábado",emoji:"⭐",titulo:"PROVA",cor:"#854D0E",objetivo:"Aplicar o manejo preparado",itens:["Observar entrada no pombal","Registrar chegada e velocidade","Avaliar peito, penas e comportamento","Alimentação conforme protocolo","Água limpa disponível"],alimentacao:"Grãos pequenos e refeição ajustada ao horário de enceste",mix:"Sem Mix Final no dia",dica:"Resultado deve ser analisado junto da recuperação, clima e consistência."},
];
const MISTURA=[["Milho pequeno",40,"#EAB308","Carboidrato principal"],["Trigo",25,"#3B82F6","Complexo B e proteína moderada"],["Sorgo",20,"#F97316","Grão leve"],["Ervilha",10,"#22C55E","Proteína moderada"],["Girassol pequeno",5,"#A78BFA","Gordura em pequena proporção"]] as const;
const TECNICAS=[
  ["01","🐦","Soltura em Pequenos Grupos","Evoluir para soltura individual somente com aves experientes.",["Começar em grupo pequeno","Aumentar autonomia gradualmente","Usar rota e clima seguros","Interromper se houver desorientação"],"Autonomia sem exposição desnecessária."],
  ["02","🧭","Variação de Direção","Evitar dependência de uma única linha.",["Variar uma condição por vez","Manter distâncias conhecidas ao mudar direção","Registrar retorno","Recuar diante de atraso"],"Orientação progressiva e mensurável."],
  ["03","🌤️","Condições Seguras Variadas","Treinar apenas com visibilidade e clima adequados.",["Luz e horário podem variar moderadamente","Vento leve pode ser registrado","Nunca usar neblina ou tempestade","Evitar calor extremo"],"Adaptação sem comprometer segurança."],
  ["04","💥","Sessões Curtas de Qualidade","Trabalhar potência sem voo forçado.",["Sessões breves conforme forma","Observar respiração e recuperação","Não impedir pouso de ave fatigada","Descanso completo depois"],"Consistência com menor risco de sobrecarga."],
] as const;
const ERROS=[["🍖","Excesso de proteína","Pode aumentar peso e desequilibrar a dieta."],["🫙","Excesso de gordura","Pode comprometer condição corporal e explosão."],["🏃","Treino longo demais","Volume excessivo reduz recuperação."],["💧","Pombal úmido","Umidade favorece problemas respiratórios e sanitários."],["😴","Baixa recuperação","Ave cansada não deve treinar nem competir."]] as const;
const SINAIS=[["🚀","Entrada eficiente","Retorna e entra sem longa circulação"],["💪","Condição corporal adequada","Musculatura firme sem excesso de peso"],["🌬️","Respiração recuperada","Sem esforço respiratório anormal"],["✨","Penas bem cuidadas","Aspecto compatível com saúde e manejo"],["👁️","Atenção e vitalidade","Comportamento alerta, sem prostração"],["⚡","Resposta consistente","Desempenho repetível, não apenas um resultado isolado"]] as const;
const CUSTOS:Record<string,number>={"Milho pequeno":2.4,Trigo:2.8,Sorgo:2.1,Ervilha:4.5,"Girassol pequeno":6};

export default function VelocidadeExtrema(){
  const[tab,setTab]=useState<Tab>("protocolo");const[diaSel,setDiaSel]=useState(0);const[pombos,setPombos]=useState(30);useEffect(()=>setPombos(loadConfig().quantidadePombos),[]);const dia=DIAS[diaSel];
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}><Link href="/centro-provas" style={{...T.btnGhost,display:"inline-block",textDecoration:"none",marginBottom:16}}>← Voltar</Link>
    <header style={{padding:20,marginBottom:16,textAlign:"center",borderRadius:14,background:"linear-gradient(135deg,#7F1D1D,#1a0505)",border:`2px solid ${T.gold}`}}><div style={{fontSize:36}}>⚡</div><h1 style={{...T.h1,color:T.gold,fontSize:24}}>Velocidade Extrema</h1><p style={{...T.small,fontSize:13}}>Protocolo de sprint com progressão e recuperação<br/><b style={{color:T.gold}}>Consistência, condição e motivação segura</b></p></header>
    <nav style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:16}}>{([['protocolo','📅 Protocolo'],['mistura','🌾 Mistura'],['tecnicas','💥 Técnicas'],['erros','⚠️ Erros'],['sinais','🏆 Sinais']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:"9px 6px",borderRadius:9,fontSize:11,fontWeight:800,color:tab===k?T.bg:T.dim,background:tab===k?T.gold:T.bgCard,border:`1px solid ${tab===k?T.gold:T.border}`}}>{l}</button>)}</nav>
    {tab==="protocolo"&&<><div style={{display:"flex",gap:4,overflowX:"auto",marginBottom:14}}>{DIAS.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{minWidth:70,padding:9,borderRadius:9,color:T.white,background:diaSel===i?d.cor:T.bgCard,border:`1px solid ${diaSel===i?d.cor:T.border}`}}><div>{d.emoji}</div><small>{d.dia.slice(0,3)}</small></button>)}</div><DiaCard dia={dia}/><section style={T.card}><Title>📋 Resumo da Semana</Title>{DIAS.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{width:"100%",display:"flex",gap:9,alignItems:"center",padding:9,marginBottom:5,textAlign:"left",borderRadius:8,color:T.white,background:diaSel===i?`${d.cor}18`:"#ffffff05",border:`1px solid ${diaSel===i?d.cor:T.border}`}}><span>{d.emoji}</span><div style={{flex:1}}><b>{d.dia} — {d.titulo}</b><div style={T.small}>{d.objetivo}</div></div>{d.destaque&&<span>⭐</span>}</button>)}</section></>}
    {tab==="mistura"&&<><section style={{...T.card,borderColor:`${T.gold}55`}}><h2 style={{color:T.gold}}>🌾 Mistura Sprint de Referência</h2><p style={T.small}>Mistura leve com predominância de carboidratos. Ajuste pela condição corporal.</p><Bar/>{MISTURA.map(([n,p,c,o])=><Ingrediente key={n} nome={n} pct={p} cor={c} obs={o}/>)}</section><section style={T.card}><Title>🧮 Calculadora — lote de 10kg</Title><Field label="🐦 Pombos velocistas"><input type="number" min={1} value={pombos} onChange={e=>setPombos(+e.target.value)} style={{...T.input,textAlign:"center",fontSize:20,fontWeight:900}}/></Field><p style={T.small}>Plantel configurado: {pombos} aves • água de referência: ~{Math.max(1,Math.ceil(pombos*.05))}L/dia</p>{MISTURA.map(([n,p,c])=>{const kg=p/10,custo=kg*(CUSTOS[n]||3);return <div key={n} style={{display:"flex",justifyContent:"space-between",padding:"8px 10px",marginBottom:5,borderRadius:8,background:`${c}0d`}}><span><i style={{display:"inline-block",width:7,height:7,borderRadius:"50%",background:c,marginRight:7}}/>{n}</span><b style={{color:c}}>{kg.toFixed(1)}kg <small style={{color:T.dim}}>R${custo.toFixed(2)}</small></b></div>})}<Info color={T.gold}>TOTAL estimado: R${MISTURA.reduce((s,[n,p])=>s+p/10*(CUSTOS[n]||3),0).toFixed(2)} por 10kg</Info></section></>}
    {tab==="tecnicas"&&<><Intro emoji="💥" title="Técnicas de Treino Seguro" color={T.red}/>{TECNICAS.map(([num,e,t,d,como,r])=><section key={num} style={{...T.card,borderLeft:`4px solid ${T.gold}`}}><div style={{display:"flex",gap:11}}><span style={{fontSize:28}}>{e}</span><div><small style={{color:T.gold}}>TÉCNICA #{num}</small><h3 style={{margin:"2px 0"}}>{t}</h3><p style={T.small}>{d}</p></div></div>{como.map(v=><div key={v} style={{padding:"6px 9px",marginBottom:4,borderRadius:7,background:"#ffffff06",fontSize:12}}>→ {v}</div>)}<Info color={T.green}>Resultado esperado: {r}</Info></section>)}<div style={{padding:10,borderRadius:9,color:T.blue,background:`${T.blue}12`,fontSize:11}}>ℹ️ Suplementos e eletrólitos devem seguir o rótulo da apresentação indicada para aves e orientação profissional.</div></>}
    {tab==="erros"&&<><Intro emoji="⚠️" title="Erros que Comprometem a Velocidade" color={T.red}/>{ERROS.map(([e,t,d])=><section key={t} style={{...T.card,borderLeft:`4px solid ${T.red}`,display:"flex",gap:11}}><span style={{fontSize:29}}>{e}</span><div><b>{t}</b><p style={{...T.small,fontSize:13}}>{d}</p></div></section>)}<Info color={T.gold}>🧠 Motivação deve usar vínculo e rotina, nunca privação, medo ou estresse.</Info></>}
    {tab==="sinais"&&<><Intro emoji="🏆" title="Sinais de Boa Preparação" color={T.gold}/>{SINAIS.map(([e,t,d])=><section key={t} style={{...T.card,display:"flex",gap:12,alignItems:"center"}}><span style={{fontSize:30}}>{e}</span><div><b style={{color:T.gold}}>{t}</b><div style={T.small}>{d}</div></div></section>)}<section style={T.card}><Title>📊 Avaliação responsável</Title><p style={{...T.small,fontSize:13,lineHeight:1.7}}>Use sinais físicos, histórico, clima e recuperação em conjunto. Nenhum checklist garante resultado, e aves com sinais clínicos não devem ser encestadas.</p></section></>}
  </div><style jsx global>{`button,input{font-family:inherit}button{cursor:pointer}`}</style></main>
}
function DiaCard({dia}:{dia:Dia}){return <section style={{padding:16,marginBottom:12,borderRadius:14,background:`${dia.cor}15`,border:`2px solid ${dia.cor}55`}}><div style={{display:"flex",gap:12,alignItems:"center"}}><span style={{fontSize:36}}>{dia.emoji}</span><div><small style={{color:T.gold}}>{dia.dia.toUpperCase()}</small><h2 style={{margin:0,fontSize:20}}>{dia.titulo}</h2><div style={T.small}>{dia.objetivo}</div></div></div><div style={{marginTop:12}}>{dia.itens.map(v=><div key={v} style={{padding:"7px 9px",marginBottom:5,borderRadius:7,background:"#ffffff06",fontSize:12}}>• {v}</div>)}</div><Info color={T.gold}>🌾 {dia.alimentacao}</Info><Info color="#A78BFA">⚗️ {dia.mix}</Info><Info color={dia.destaque?T.gold:T.dim}>💡 {dia.dica}</Info></section>}
function Bar(){return <div style={{display:"flex",height:15,borderRadius:8,overflow:"hidden",margin:"12px 0"}}>{MISTURA.map(([,p,c])=><div key={c} style={{flex:p,background:c}}/>)}</div>}
function Ingrediente({nome,pct,cor,obs}:{nome:string;pct:number;cor:string;obs:string}){return <div style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between"}}><b><span style={{color:cor}}>■</span> {nome}</b><b style={{color:cor}}>{pct}%</b></div><div style={{height:4,marginTop:3,background:"#ffffff14"}}><div style={{height:"100%",width:`${pct}%`,background:cor}}/></div><small style={{color:T.dim}}>{obs}</small></div>}
function Intro({emoji,title,color}:{emoji:string;title:string;color:string}){return <section style={{...T.card,textAlign:"center",border:`2px solid ${color}55`}}><div style={{fontSize:32}}>{emoji}</div><b style={{color}}>{title}</b></section>}
function Info({children,color}:{children:React.ReactNode;color:string}){return <div style={{padding:9,marginTop:8,borderRadius:8,color,background:`${color}12`,border:`1px solid ${color}44`,fontSize:12,lineHeight:1.6}}>{children}</div>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:10}}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:10}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
