"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { loadConfig } from "../config";
import { T } from "../theme";

type Aba = "protocolo" | "mistura" | "recuperacao" | "segredos";
type Dia = { dia: string; emoji: string; titulo: string; cor: string; objetivo: string; itens: { icon: string; txt: string }[]; alim: string; mix: string; dica: string; urgente?: boolean; destaque?: boolean };

const PROTOCOLO: Dia[] = [
  { dia: "Domingo", emoji: "💙", titulo: "Recuperação Total", cor: "#1E3A5F", objetivo: "As primeiras 24h são as mais importantes do calendário", itens: [["⚡","IMEDIATO ao retorno: eletrólitos + glicose na água"],["💊","Aminomix 1,5g/L — aminoácidos para músculo destruído"],["🌾","Cevada depurativa + arroz com casca — levíssimo"],["🛁","Banho morno obrigatório — relaxar musculatura"],["💉","Bioxan 3mL/L — vitaminas B + repor energia"],["😴","ZERO treino — descanso máximo absoluto"]].map(([icon,txt])=>({icon,txt})), alim: "LEVE: Cevada 60% + Arroz c/casca 25% + Trigo 15% — depurativo", mix: "Sem mix — dia de depuração (opcional: 1g/pombo)", dica: "Fundo extremo destrói fibras musculares, esgota eletrólitos e consome reservas. A recuperação começa NO MOMENTO do retorno!", urgente: true },
  { dia: "Segunda", emoji: "🟢", titulo: "Recuperação Ativa", cor: "#166534", objetivo: "Reconstrução muscular e flora intestinal", itens: [["🦠","Organew 5g/ração — probiótico essencial pós-esforço"],["💪","Aminomix 1,5g/L — continuar reconstrução muscular"],["💉","Bioxan 2mL/L — vitaminas e energia"],["🏃","Voo livre apenas 20-30 minutos — sem pressão"],["💧","Eletrólitos disponíveis o dia todo"]].map(([icon,txt])=>({icon,txt})), alim: "Milho 35% + Trigo 25% + Sorgo 20% + Arroz 15% + Ervilha 5%", mix: "1,5g/pombo misturado na ração", dica: "O intestino do fundista sofre muito. Probióticos são obrigatórios nos 3 dias pós-prova." },
  { dia: "Terça", emoji: "🟡", titulo: "Reconstrução + Treino Leve", cor: "#854D0E", objetivo: "Retornar gradualmente ao condicionamento", itens: [["📏","Soltura curta 40-60 km — ritmo leve, sem forçar"],["⚡","Eletrólitos pós-treino — reposição mineral"],["💊","Aminomix 1g/L + Organew 5g/ração"],["🕐","Registrar tempo — comparar com padrão"],["👁️","Observar fezes — devem estar normalizando"]].map(([icon,txt])=>({icon,txt})), alim: "Milho 40% + Trigo 20% + Sorgo 20% + Arroz c/casca 10% + Girassol 10%", mix: "2g/pombo misturado na ração", dica: "Se o pombo parece cansado ou com fezes alteradas após 60km, precisa de mais recuperação." },
  { dia: "Quarta", emoji: "🔵", titulo: "Treino de Resistência", cor: "#1E3A5F", objetivo: "Reconstruir capacidade aeróbica do fundista", itens: [["📏","Soltura 80-150 km — ritmo constante e controlado"],["⏱️","Voo livre 45-60 minutos antes da soltura"],["🫁","Foco em pulmão e cardiovascular — não em velocidade"],["💊","Vitamina E + Aminomix 1g/L pós-treino"],["🔋","L-Carnitina + CoQ10 — energia celular (avançado)"]].map(([icon,txt])=>({icon,txt})), alim: "Alta gordura boa: Milho 35% + Girassol 20% + Trigo 15% + Sorgo 15% + Amendoim 10% + Ervilha 5%", mix: "2g/pombo misturado na ração", dica: "O fundista precisa de gordura boa. Girassol e amendoim liberam energia lentamente.", destaque: true },
  { dia: "Quinta", emoji: "🟠", titulo: "Carga Energética Máxima", cor: "#9A3412", objetivo: "Acumular a máxima reserva para o fundo", itens: [["⚗️","MIX FINAL 3g/pombo sobre a ração — DOSE MÁXIMA"],["🌾","Mistura ENERGÉTICA — mais oleaginosas"],["💊","Potenfort (se usar) — 2-3 dias antes da prova longa"],["⚡","Eletrólitos + Aminomix"],["😌","Sem treino intenso — só voo livre leve"]].map(([icon,txt])=>({icon,txt})), alim: "ALTA ENERGIA: Milho 35% + Girassol 20% + Amendoim 15% + Linhaça 10% + Trigo 10% + Ervilha 10%", mix: "3g/pombo — DOSE MÁXIMA (sobre a ração)", dica: "Esta é a carga mais importante do fundo. A gordura de quinta sustenta o voo longo.", destaque: true },
  { dia: "Sexta", emoji: "🟣", titulo: "Carga Final + Encestamento", cor: "#4C1D95", objetivo: "Última carga e enceste na condição máxima", itens: [["🌾","Manhã: mistura energética — última refeição forte"],["⚡","Eletrólitos + mel na água — hidratação total"],["❤️","Viuvez: apresentar fêmea (macho) — motivação máxima"],["💊","Bioxan 2mL/L + Aminomix 1g/L"],["🏁","Tarde: encestamento tranquilo — verificar condição"]].map(([icon,txt])=>({icon,txt})), alim: "Manhã: Milho 40% + Girassol 20% + Linhaça 20% + Trigo 20% — Tarde: muito leve", mix: "2g/pombo de manhã — última dose", dica: "No enceste ideal: musculatura elástica, asa leve e peito firme.", destaque: true },
  { dia: "Sáb/Dom", emoji: "⭐", titulo: "PROVA DE FUNDO EXTREMO", cor: "#065F46", objetivo: "O resultado de meses de trabalho", itens: [["🌅","Água com mel + eletrólitos antes da soltura"],["👁️","Verificar: musculatura elástica, asa leve, olhar vivo"],["📊","Registrar hora de soltura, clima e vento"],["⏱️","Monitorar retorno — pode ser 12-36h depois"],["🔄","Preparar recuperação: eletrólitos prontos para chegada"]].map(([icon,txt])=>({icon,txt})), alim: "Levíssimo na manhã: Grãos pequenos apenas", mix: "Sem Mix — prova", dica: "Campeão de fundo é construído em meses, não em dias!" },
];

const GRAOS = [
  ["Milho energético",35,"#EAB308","Carboidrato principal"],["Girassol",20,"#F97316","Gordura boa — energia longa"],["Amendoim",15,"#FB923C","Gordura + proteína — reserva"],["Linhaça",10,"#A78BFA","Ômega 3 + anti-inflamatório"],["Trigo",10,"#3B82F6","Complexo B + proteína"],["Ervilha",10,"#22C55E","Proteína moderada"],
] as const;
const MIX = [
  ["Aveia",250,"#EAB308","Energia de liberação lenta — 12-16h"],["Amido de batata",150,"#3B82F6","Carboidrato rápido + reserva"],["Proteína de soja",120,"#22C55E","Proteína muscular de alto valor"],["Levedura de cerveja",60,"#A78BFA","Vitaminas B + flora"],["Spirulina",30,"#06B6D4","Proteína completa + antioxidante"],["Beterraba (pó)",20,"#EF4444","Circulação + oxigenação"],["Cenoura (pó)",15,"#F97316","Vitamina A + visão"],["Espinafre (pó)",15,"#22C55E","Ferro + hemoglobina"],["Alho (pó)",5,"#94A3B8","Imunidade natural"],["Cebola (pó)",3,"#FBBF24","Flavonoides + circulação"],["Beta-alanina",5,"#F472B6","Reduz fadiga aeróbica"],["Creatina",8,"#60A5FA","Reserva energética muscular"],["Farinha de amendoim",140,"#FB923C","Gordura boa + proteína"],["Farinha de girassol",90,"#EAB308","Gordura + vitamina E"],["Farinha de linhaça",60,"#A78BFA","Ômega 3"],["Farinha de peixe",25,"#60A5FA","Proteína animal + ômega 3"],
] as const;
const FASES = [
  { tempo:"Retorno imediato (0-2h)", cor:T.red, emoji:"⚡", itens:["Eletrólitos + glicose na água — IMEDIATO","Aminomix 1,5g/L — aminoácidos agora","Mel puro 5g/L — energia rápida","Ambiente tranquilo — sem estresse","Não pegar o pombo bruscamente"] },
  { tempo:"Primeiras 24h", cor:"#FBBF24", emoji:"🌅", itens:["Alimentação leve: cevada + arroz","Bioxan 3mL/L","Organew 5g/ração","ZERO treino","Banho morno à tarde"] },
  { tempo:"48-72h pós-prova", cor:T.orange, emoji:"🔄", itens:["Volta gradual da energia","Aminomix continua","Voo livre leve 20-30min","Vitamina E","Observar fezes"] },
  { tempo:"3-5 dias após", cor:T.green, emoji:"✅", itens:["Ração normal","Treino curto 30-50km","Verificar resposta","Se cansado: mais descanso","Nunca forçar"] },
];
const SINAIS = [["⚖️","Musculatura elástica","Nem gordo, nem magro"],["🪶","Asa leve e deslizante","Aerodinâmica perfeita"],["💊","Recuperação excelente","Normal em 48-72h"],["🦠","Intestino funcionando","Fezes normais"],["👁️","Olhar concentrado","Vitalidade interna"],["🫁","Respiração limpa","Sem chiado"]] as const;

export default function FundoExtremo() {
  const [tab, setTab] = useState<Aba>("protocolo");
  const [diaSel, setDiaSel] = useState(0);
  const [pombos, setPombos] = useState(20);
  useEffect(() => setPombos(loadConfig().quantidadePombos), []);
  const dia = PROTOCOLO[diaSel];
  const totalMix = MIX.reduce((sum, item) => sum + item[1], 0);

  return <main style={{ minHeight:"100vh", background:T.bg, color:T.white, padding:"18px 12px 50px" }}><div style={{ maxWidth:760, margin:"0 auto" }}>
    <Link href="/centro-provas" style={{ ...T.btnGhost, display:"inline-block", textDecoration:"none", marginBottom:16 }}>← Voltar</Link>
    <header style={{ background:"linear-gradient(135deg,#1c0a00,#0a0a1a)", border:`2px solid ${T.orange}`, borderRadius:14, padding:20, marginBottom:16, textAlign:"center" }}><div style={{fontSize:40}}>🦅</div><h1 style={{...T.h1,color:T.orange,fontSize:24}}>Fundo Extremo</h1><p style={{...T.small,fontSize:13}}>800–1200 km • Máxima resistência<br/><b style={{color:T.orange}}>Construído em meses — vencido em horas</b></p><div style={{display:"flex",gap:7,justifyContent:"center",flexWrap:"wrap"}}>{["Reserva energética","Pulmão forte","Intestino saudável","Recuperação rápida"].map(v=><span key={v} style={{fontSize:10,padding:"4px 10px",borderRadius:20,background:"#f9731633",color:T.orange}}>✓ {v}</span>)}</div></header>
    <nav style={{display:"flex",gap:5,marginBottom:16}}>{([['protocolo','📅 Protocolo'],['mistura','🌾 Mistura'],['recuperacao','🔄 Recuperação'],['segredos','🏆 Segredos']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:"9px 4px",borderRadius:10,cursor:"pointer",fontSize:11,fontWeight:800,background:tab===k?T.orange:T.bgCard,color:tab===k?T.white:T.dim,border:`1px solid ${tab===k?T.orange:T.border}`}}>{l}</button>)}</nav>

    {tab==="protocolo"&&<><div style={{display:"flex",gap:4,overflowX:"auto",marginBottom:13}}>{PROTOCOLO.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{minWidth:70,padding:9,borderRadius:9,cursor:"pointer",background:diaSel===i?d.cor:T.bgCard,color:T.white,border:`1px solid ${diaSel===i?d.cor:T.border}`}}><div>{d.emoji}</div><small>{d.dia.slice(0,3)}</small></button>)}</div><DiaCard dia={dia}/><section style={T.card}><Title>📋 Semana Completa</Title>{PROTOCOLO.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{width:"100%",display:"flex",alignItems:"center",gap:9,textAlign:"left",padding:9,marginBottom:5,borderRadius:8,cursor:"pointer",color:T.white,background:diaSel===i?`${d.cor}22`:"#ffffff05",border:`1px solid ${diaSel===i?d.cor:T.border}`}}><span>{d.emoji}</span><b>{d.dia}</b><span style={{...T.small,flex:1}}>{d.titulo}</span>{d.destaque&&<em style={{color:T.orange}}>⭐</em>}{d.urgente&&<em>🚨</em>}</button>)}</section></>}

    {tab==="mistura"&&<><section style={{...T.card,borderColor:"#f9731655"}}><h2 style={{color:T.orange,fontSize:15}}>🌾 Mistura de Grãos — Fundo Extremo</h2><p style={T.small}>Alta energia lipídica para 800-1200km.</p><Bar items={GRAOS.map(v=>({value:v[1],color:v[2]}))}/>{GRAOS.map(([nome,pct,cor,obs])=><Ingredient key={nome} name={nome} value={`${pct}%`} color={cor} obs={obs}/>)}</section><section style={T.card}><h2 style={{color:"#A78BFA",fontSize:15}}>⚗️ Mix Final Fundo Extremo (1kg)</h2><p style={T.small}>Dose REAL: <b>2–3g/pombo misturado na ração</b> (com fio de óleo pra grudar) — Quarta a Sexta • completo em <Link href="/centro-provas/mix-energetico" style={{color:T.blue}}>⚗️ Mix Energético</Link></p><Bar items={MIX.map(v=>({value:v[1],color:v[2]}))}/>{MIX.map(([nome,g,cor,obs])=><Ingredient key={nome} name={nome} value={`${g}g`} color={cor} obs={obs}/>)}<Info color="#A78BFA">⚗️ Total: {totalMix}g | Mix rico em gordura boa para energia longa</Info></section><section style={T.card}><Title>🧮 Calculadora</Title><input type="number" min={1} value={pombos} onChange={e=>setPombos(+e.target.value)} style={{...T.input,textAlign:"center",fontSize:20,fontWeight:900,marginBottom:10}}/><div className="calc-results" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[["Mix/semana (3x)",`${(pombos*.0075).toFixed(2)}kg`,"#A78BFA"],["Grãos/dia",`${(pombos*.035).toFixed(2)}kg`,T.orange],["Lote 1kg dura",`${Math.max(1,Math.round(1.056/(pombos*.0075)))} sem.`,T.gold],["Custo mix/mês",`R$${(pombos*2.1).toFixed(2)}`,T.green]].map(([l,v,c])=><Metric key={l} label={l} value={v} color={c}/>)}</div></section></>}

    {tab==="recuperacao"&&<><section style={{...T.card,border:`2px solid ${T.red}88`,background:"#ef444414"}}><h2 style={{color:T.red,fontSize:14}}>🚨 As Primeiras 24h São as Mais Importantes!</h2><p style={{fontSize:13,lineHeight:1.8}}>Após 800-1200km, o pombo perdeu fluidos, esgotou reservas, destruiu fibras musculares e comprometeu a flora intestinal.<br/><b style={{color:T.red}}>A recuperação começa NO MOMENTO do retorno!</b></p></section>{FASES.map(f=><section key={f.tempo} style={{...T.card,borderLeft:`4px solid ${f.cor}`}}><h3 style={{color:f.cor,fontSize:14}}>{f.emoji} {f.tempo}</h3>{f.itens.map(v=><div key={v} style={{fontSize:12,padding:"5px 0",borderBottom:"1px solid #ffffff0a"}}><span style={{color:f.cor}}>→</span> {v}</div>)}</section>)}<section style={T.card}><Title>⚠️ Sinais de Excesso de Treino</Title>{[["Peito seco demais","Reserva esgotada"],["Penas opacas","Déficit nutricional"],["Sede excessiva","Desidratação crônica"],["Queda de rendimento","Overtraining"],["Demora na recuperação","Sistema exausto"]].map(([a,b])=><div key={a} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"8px 0",borderBottom:`1px solid ${T.border}`,fontSize:12}}><b style={{color:T.red}}>⚠️ {a}</b><span style={{color:T.dim}}>{b}</span></div>)}</section></>}

    {tab==="segredos"&&<><section style={{...T.card,textAlign:"center",border:`2px solid ${T.orange}66`}}><div style={{fontSize:36}}>🏆</div><b style={{color:T.orange}}>Sinais do Campeão de Fundo Extremo</b></section>{SINAIS.map(([e,s,d])=><section key={s} style={{...T.card,display:"flex",gap:12,alignItems:"center"}}><span style={{fontSize:28}}>{e}</span><div><b style={{color:T.orange}}>{s}</b><div style={T.small}>{d}</div></div></section>)}<section style={{...T.card,border:`2px solid ${T.orange}66`}}><Title>🎯 O Ponto Ideal do Fundista</Title><p style={{fontSize:13,lineHeight:1.9}}><span style={{color:T.red}}>❌ Não pode estar gordo</span><br/><span style={{color:T.red}}>❌ Não pode estar magro</span><br/><span style={{color:T.red}}>❌ Menos proteína pesada</span><br/><br/><b style={{color:T.orange}}>✅ Precisa estar ELÁSTICO:</b><br/>• Musculatura firme e elástica<br/>• Asa leve e deslizante<br/>• Recuperação excelente<br/>• Intestino funcionando<br/>• Alta reserva energética lipídica</p></section><section style={T.card}><Title>💊 Suplementos Avançados para Fundo</Title>{[["🔋","L-Carnitina","Transporte de gordura para energia","Terça e Quinta"],["⚡","CoQ10","Energia celular mitocondrial","Terça e Quinta"],["💙","Taurina","Proteção cardíaca","Toda semana"],["⚗️","Beta-alanina","Reduz acidose muscular","No Mix Quinta"],["🔋","Potenfort","Estimulante cardiovascular","2-3 dias antes"]].map(([e,n,u,q])=><div key={n} style={{display:"flex",gap:10,padding:"10px 0",borderBottom:`1px solid ${T.border}`}}><span>{e}</span><div><b style={{color:T.gold}}>{n}</b><div style={T.small}>{u}</div><small style={{color:T.orange}}>📅 {q}</small></div></div>)}</section></>}
  </div><style jsx global>{`button,input{font-family:inherit}@media(max-width:520px){.calc-results{grid-template-columns:1fr 1fr!important}}`}</style></main>;
}

function DiaCard({dia}:{dia:Dia}){return <section style={{background:`${dia.cor}20`,border:`2px solid ${dia.urgente?T.red:dia.cor}77`,borderRadius:14,padding:16,marginBottom:12}}>{dia.urgente&&<Info color={T.red}>🚨 PRIORIDADE MÁXIMA — Fazer imediatamente ao retorno!</Info>}<div style={{display:"flex",gap:12,alignItems:"center",marginBottom:12}}><span style={{fontSize:36}}>{dia.emoji}</span><div><small style={{color:T.orange}}>{dia.dia.toUpperCase()}</small><h2 style={{margin:0,fontSize:20}}>{dia.titulo}</h2><div style={T.small}>{dia.objetivo}</div></div></div>{dia.itens.map(v=><div key={v.txt} style={{display:"flex",gap:9,padding:"8px 10px",marginBottom:5,borderRadius:8,background:"#ffffff08",fontSize:13}}><span>{v.icon}</span><span>{v.txt}</span></div>)}<Info color={T.orange}>🌾 <b>ALIMENTAÇÃO:</b> {dia.alim}</Info><Info color="#A78BFA">⚗️ <b>MIX FINAL:</b> {dia.mix}</Info><Info color={dia.destaque?T.orange:T.dim}>{dia.destaque?"⭐ FUNDAMENTAL":"💡 DICA"}: {dia.dica}</Info></section>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.orange,marginBottom:10}}>{children}</div>}
function Info({children,color}:{children:React.ReactNode;color:string}){return <div style={{padding:"9px 11px",marginBottom:8,borderRadius:8,background:`${color}15`,border:`1px solid ${color}55`,fontSize:12,color}}>{children}</div>}
function Bar({items}:{items:{value:number;color:string}[]}){return <div style={{display:"flex",height:12,borderRadius:7,overflow:"hidden",margin:"12px 0"}}>{items.map((v,i)=><div key={i} style={{flex:v.value,background:v.color}}/>)}</div>}
function Ingredient({name,value,color,obs}:{name:string;value:string;color:string;obs:string}){return <div style={{padding:"7px 0",borderBottom:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between"}}><b style={{fontSize:12}}><span style={{color}}>●</span> {name}</b><b style={{color}}>{value}</b></div><div style={{...T.small,fontSize:10}}>{obs}</div></div>}
function Metric({label,value,color}:{label:string;value:string;color:string}){return <div style={{padding:10,textAlign:"center",borderRadius:8,background:`${color}12`,border:`1px solid ${color}44`}}><div style={T.small}>{label}</div><b style={{color,fontSize:16}}>{value}</b></div>}
