"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { loadCalendario } from "../data/calendario";
import { T } from "../theme";

type Tipo = "prova"|"treino"|"tratamento"|"reproducao"|"sanitario"|"alimentacao"|"outro";
type Evento = { id:string; titulo:string; data:string; dataFim?:string; tipo:Tipo; descricao?:string; recorrente?:boolean; calendario?:boolean };
type Vista = "ano"|"mes"|"form";
const KEY="nutripombos-planejamento-v1";
const MESES=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const DIAS=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
const CFG:Record<Tipo,{label:string;emoji:string;cor:string}>={prova:{label:"Prova",emoji:"🏁",cor:"#EAB308"},treino:{label:"Treino",emoji:"🏋️",cor:"#3B82F6"},tratamento:{label:"Saúde",emoji:"💉",cor:"#EF4444"},reproducao:{label:"Reprodução",emoji:"🥚",cor:"#F472B6"},sanitario:{label:"Higiene",emoji:"🧹",cor:"#22C55E"},alimentacao:{label:"Alimentação",emoji:"🌾",cor:"#A78BFA"},outro:{label:"Outro",emoji:"📌",cor:"#94A3B8"}};
const BASE:Evento[]=[
  {id:"s1",titulo:"Avaliação sanitária preventiva",data:"2026-01-15",tipo:"tratamento",recorrente:true,descricao:"Revisar peso, fezes e necessidade de exames com veterinário"},
  {id:"s2",titulo:"Revisão do protocolo vacinal",data:"2026-02-10",tipo:"tratamento",descricao:"Confirmar indicação e calendário com médico-veterinário"},
  {id:"s3",titulo:"Exame de fezes",data:"2026-02-28",tipo:"sanitario",descricao:"Pesquisa de parasitas antes da temporada"},
  {id:"s4",titulo:"Desinfecção do pombal",data:"2026-01-05",tipo:"sanitario",recorrente:true,descricao:"Limpeza planejada, ventilação e controle de umidade"},
  {id:"r1",titulo:"Período de reprodução",data:"2026-01-01",dataFim:"2026-03-31",tipo:"reproducao",descricao:"Acasalamento e primeira ninhada"},
  {id:"r2",titulo:"Segunda ninhada (opcional)",data:"2026-04-01",dataFim:"2026-05-31",tipo:"reproducao",descricao:"Conforme condição dos casais"},
  {id:"t1",titulo:"Início dos treinos curtos",data:"2026-04-15",tipo:"treino",descricao:"30–50km — adaptação"},
  {id:"t2",titulo:"Treinos médios",data:"2026-05-01",tipo:"treino",descricao:"80–120km — progressão"},
  {id:"t3",titulo:"Treinos longos",data:"2026-05-15",tipo:"treino",descricao:"150–300km — preparação final"},
  {id:"a1",titulo:"Protocolo de competição",data:"2026-06-01",tipo:"alimentacao",descricao:"Ajustar consumo e condição corporal"},
  {id:"a2",titulo:"Muda das penas",data:"2026-09-01",dataFim:"2026-11-30",tipo:"alimentacao",descricao:"Revisar proteína, minerais e qualidade das penas"},
  {id:"a3",titulo:"Ração de manutenção",data:"2026-12-01",tipo:"alimentacao",descricao:"Dieta de descanso pós-temporada"},
  {id:"p1",titulo:"Planejamento da próxima temporada",data:"2026-12-15",tipo:"outro",descricao:"Revisar resultados, plantel e objetivos"},
];
function read():Evento[]{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)&&v.length?v:BASE}catch{return BASE}}
function days(y:number,m:number){return new Date(y,m+1,0).getDate()}
function first(y:number,m:number){return new Date(y,m,1).getDay()}
function date(y:number,m:number,d:number){return `${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`}
function fmt(v:string){const[a,m,d]=v.split("-");return`${d}/${m}/${a}`}

export default function PlanejamentoAnual(){
  const[eventos,setEventos]=useState<Evento[]>([]);const[ready,setReady]=useState(false);const[ano,setAno]=useState(2026);const[mes,setMes]=useState(new Date().getMonth());const[diaSel,setDiaSel]=useState<string|null>(null);const[vista,setVista]=useState<Vista>("ano");const[filtros,setFiltros]=useState<Tipo[]>(Object.keys(CFG) as Tipo[]);const[editId,setEditId]=useState<string|null>(null);const[form,setForm]=useState<Partial<Evento>>({tipo:"outro"});
  useEffect(()=>{const custom=read().filter(e=>!e.calendario);const provas=loadCalendario().map(p=>({id:`cal-${p.id||p.num}`,titulo:`#${p.num} ${p.cidade}/${p.estado} — ${p.km}km`,data:p.dataSolta,tipo:"prova" as Tipo,descricao:`Embarque: ${p.dataEmbarque} (${p.diaEmbarque})`,calendario:true}));setEventos([...custom,...provas]);setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(eventos.filter(e=>!e.calendario)))},[eventos,ready]);
  const filtrados=useMemo(()=>eventos.filter(e=>filtros.includes(e.tipo)),[eventos,filtros]);
  const noDia=(v:string)=>filtrados.filter(e=>e.data===v||(e.dataFim&&v>=e.data&&v<=e.dataFim));
  const noMes=(y:number,m:number)=>{const p=`${y}-${String(m+1).padStart(2,"0")}`;return filtrados.filter(e=>e.data.startsWith(p)||(e.dataFim&&p>=e.data.slice(0,7)&&p<=e.dataFim.slice(0,7)))};
  function abrir(data?:string,e?:Evento){setForm(e?{...e}:{tipo:"outro",data:data||date(ano,mes,1)});setEditId(e?.id||null);setVista("form")}
  function salvar(){if(!form.titulo?.trim()||!form.data){alert("Título e data são obrigatórios.");return}if(editId)setEventos(v=>v.map(e=>e.id===editId?{...e,...form} as Evento:e));else setEventos(v=>[...v,{id:crypto.randomUUID(),...form} as Evento]);setForm({tipo:"outro"});setEditId(null);setVista("mes")}
  function excluir(id:string){if(confirm("Excluir este evento?"))setEventos(v=>v.filter(e=>e.id!==id))}

  if(vista==="form")return <Shell><button onClick={()=>setVista("mes")} style={{...T.btnGhost,marginBottom:16}}>← Cancelar</button><h1 style={T.h1}>{editId?"✏️ Editar Evento":"➕ Novo Evento"}</h1><section style={{...T.card,marginTop:16}}><Field label="Tipo de evento"><div className="types" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{Object.entries(CFG).map(([k,c])=><button key={k} onClick={()=>setForm(v=>({...v,tipo:k as Tipo}))} style={{padding:10,borderRadius:9,textAlign:"left",color:form.tipo===k?c.cor:T.dim,background:form.tipo===k?`${c.cor}18`:T.bgInput,border:`1px solid ${form.tipo===k?c.cor:T.border}`}}>{c.emoji} {c.label}</button>)}</div></Field><Field label="Título *"><input value={form.titulo||""} onChange={e=>setForm(v=>({...v,titulo:e.target.value}))} style={T.input}/></Field><div className="date-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Field label="📅 Data *"><input type="date" value={form.data||""} onChange={e=>setForm(v=>({...v,data:e.target.value}))} style={T.input}/></Field><Field label="📅 Data fim"><input type="date" value={form.dataFim||""} onChange={e=>setForm(v=>({...v,dataFim:e.target.value||undefined}))} style={T.input}/></Field></div><Field label="📝 Descrição"><textarea rows={3} value={form.descricao||""} onChange={e=>setForm(v=>({...v,descricao:e.target.value}))} style={{...T.input,height:80}}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>setVista("mes")} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvar} style={{...T.btn,flex:2}}>💾 Salvar evento</button></div></section></Shell>;

  if(vista==="mes"){const cells:(number|null)[]=[...Array(first(ano,mes)).fill(null),...Array.from({length:days(ano,mes)},(_,i)=>i+1)];while(cells.length%7)cells.push(null);const selected=diaSel?noDia(diaSel):[];return <Shell><button onClick={()=>setVista("ano")} style={{...T.btnGhost,marginBottom:16}}>← Visão Anual</button><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><button onClick={()=>setMes((mes+11)%12)} style={T.btnGhost}>‹</button><div style={{textAlign:"center"}}><h2 style={{color:T.gold,margin:0}}>{MESES[mes]}</h2><small>{ano}</small></div><button onClick={()=>setMes((mes+1)%12)} style={T.btnGhost}>›</button></div><Filtros filtros={filtros} setFiltros={setFiltros}/><section style={{...T.card,padding:12}}><div className="calendar-grid" style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:2}}>{DIAS.map(v=><b key={v} style={{fontSize:10,textAlign:"center",color:T.dim,padding:4}}>{v}</b>)}{cells.map((d,i)=>{if(!d)return <span key={i}/>;const ds=date(ano,mes,d),ev=noDia(ds),selected=ds===diaSel,today=ds===new Date().toISOString().slice(0,10);return <button key={i} onClick={()=>setDiaSel(selected?null:ds)} style={{minHeight:52,padding:4,borderRadius:7,color:today?T.gold:T.white,background:selected?`${T.gold}20`:today?"#ffffff0d":"#ffffff05",border:`1px solid ${selected?T.gold:"transparent"}`}}><b>{d}</b><div style={{display:"flex",gap:2,justifyContent:"center",flexWrap:"wrap",marginTop:3}}>{ev.slice(0,4).map(e=><i key={e.id} style={{width:6,height:6,borderRadius:"50%",background:CFG[e.tipo].cor}}/> )}</div></button>})}</div></section>{diaSel?<DayEvents date={diaSel} eventos={selected} abrir={abrir} excluir={excluir}/>:<MonthList month={MESES[mes]} eventos={noMes(ano,mes)} abrir={()=>abrir()}/>}</Shell>}

  return <Shell><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10,marginBottom:20}}><div><Link href="/centro-provas" style={{...T.small,textDecoration:"none"}}>← Centro de Provas</Link><h1 style={{...T.h1,marginTop:9}}>📅 Planejamento Anual</h1><p style={{...T.small,marginTop:4}}>Provas, treinos, saúde, reprodução e alimentação</p></div><div style={{display:"flex",gap:5}}><button onClick={()=>setAno(ano-1)} style={T.btnGhost}>‹ {ano-1}</button><button onClick={()=>setAno(ano+1)} style={T.btnGhost}>{ano+1} ›</button></div></div><Filtros filtros={filtros} setFiltros={setFiltros}/><div style={{display:"grid",gap:8}}>{MESES.map((nome,m)=><MonthCard key={nome} nome={nome} month={m} year={ano} eventos={noMes(ano,m)} onOpen={(day)=>{setMes(m);setDiaSel(day);setVista("mes")}}/>)}</div><section style={{...T.card,marginTop:8,borderColor:`${T.gold}55`}}><Title>📊 Resumo {ano}</Title><div className="summary" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{Object.entries(CFG).map(([k,c])=><div key={k} style={{display:"flex",justifyContent:"space-between",padding:8,borderRadius:8,color:c.cor,background:`${c.cor}12`}}><span>{c.emoji} {c.label}</span><b>{filtrados.filter(e=>e.tipo===k&&e.data.startsWith(String(ano))).length}</b></div>)}</div></section></Shell>
}

function Filtros({filtros,setFiltros}:{filtros:Tipo[];setFiltros:(v:Tipo[])=>void}){return <div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:12}}>{Object.entries(CFG).map(([k,c])=>{const on=filtros.includes(k as Tipo);return <button key={k} onClick={()=>setFiltros(on?filtros.filter(v=>v!==k):[...filtros,k as Tipo])} style={{padding:"5px 9px",borderRadius:20,color:on?c.cor:T.dim2,background:on?`${c.cor}18`:"#ffffff05",border:`1px solid ${on?c.cor:T.border}`,fontSize:10}}>{c.emoji} {c.label}</button>})}</div>}
function MonthCard({nome,month,year,eventos,onOpen}:{nome:string;month:number;year:number;eventos:Evento[];onOpen:(d:string|null)=>void}){const current=new Date().getMonth()===month&&new Date().getFullYear()===year;const cells:(number|null)[]=[...Array(first(year,month)).fill(null),...Array.from({length:days(year,month)},(_,i)=>i+1)];return <section style={{...T.card,borderColor:current?`${T.gold}55`:T.border}}><button onClick={()=>onOpen(null)} style={{width:"100%",display:"flex",justifyContent:"space-between",background:"none",border:0,color:T.white,padding:0,marginBottom:8}}><b style={{color:current?T.gold:T.white}}>{current?"▶ ":""}{nome} <small style={{color:T.dim}}>{eventos.length} evento(s)</small></b><span style={{color:T.blue}}>ver mês →</span></button><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:1}}>{DIAS.map(v=><small key={v} style={{textAlign:"center",color:T.dim2}}>{v}</small>)}{cells.map((d,i)=>{if(!d)return <span key={i}/>;const ds=date(year,month,d),ev=eventos.filter(e=>e.data===ds||(e.dataFim&&ds>=e.data&&ds<=e.dataFim)),cor=ev[0]?CFG[ev[0].tipo].cor:undefined;return <button key={i} onClick={()=>onOpen(ds)} style={{minHeight:19,borderRadius:4,fontSize:9,color:cor||T.dim,background:cor?`${cor}20`:"transparent",border:0}}>{d}</button>})}</div>{eventos.slice(0,5).map(e=><div key={e.id} style={{display:"flex",gap:7,padding:"5px 7px",marginTop:4,borderRadius:7,background:`${CFG[e.tipo].cor}0d`,fontSize:11}}><i style={{width:6,height:6,borderRadius:"50%",background:CFG[e.tipo].cor,marginTop:4}}/><span style={{color:T.dim}}>{e.data.slice(8)}/{e.data.slice(5,7)}</span><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{e.titulo}</span></div>)}</section>}
function DayEvents({date,eventos,abrir,excluir}:{date:string;eventos:Evento[];abrir:(d?:string,e?:Evento)=>void;excluir:(id:string)=>void}){return <div style={{marginTop:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>{fmt(date)}</b><button onClick={()=>abrir(date)} style={T.btnSm}>+ Evento</button></div>{eventos.map(e=><section key={e.id} style={{...T.card,marginTop:8,borderLeft:`4px solid ${CFG[e.tipo].cor}`}}><small style={{color:CFG[e.tipo].cor}}>{CFG[e.tipo].emoji} {CFG[e.tipo].label} {e.calendario?"• calendário":""}</small><b style={{display:"block",marginTop:4}}>{e.titulo}</b>{e.descricao&&<p style={T.small}>{e.descricao}</p>}{!e.calendario&&<div style={{display:"flex",gap:5,justifyContent:"end"}}><button onClick={()=>abrir(date,e)} style={T.btnGhost}>✏️</button><button onClick={()=>excluir(e.id)} style={T.btnDanger}>🗑️</button></div>}</section>)}{!eventos.length&&<section style={{...T.card,textAlign:"center",color:T.dim}}>Nenhum evento neste dia.</section>}</div>}
function MonthList({month,eventos,abrir}:{month:string;eventos:Evento[];abrir:()=>void}){return <div style={{marginTop:12}}><div style={{display:"flex",justifyContent:"space-between"}}><Title>📋 Eventos de {month}</Title><button onClick={abrir} style={T.btnSm}>+ Evento</button></div>{eventos.sort((a,b)=>a.data.localeCompare(b.data)).map(e=><div key={e.id} style={{display:"flex",gap:8,padding:"8px 0",borderBottom:`1px solid ${T.border}`}}><i style={{width:7,height:7,borderRadius:"50%",background:CFG[e.tipo].cor,marginTop:5}}/><small style={{color:T.dim}}>{e.data.slice(8)}</small><span>{e.titulo}</span></div>)}</div>}
function Shell({children}:{children:React.ReactNode}){return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>{children}</div><style jsx global>{`button,input,textarea{font-family:inherit}button{cursor:pointer}@media(max-width:520px){.date-grid,.types{grid-template-columns:1fr!important}.summary{grid-template-columns:1fr 1fr!important}}`}</style></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:12}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:10}}>{children}</div>}
