"use client";

import { useState } from "react";
import Link from "next/link";
import { T } from "../theme";

type Tab="fases"|"truques"|"sinais"|"erros";
type Fase={num:string;titulo:string;emoji:string;cor:string;duracao:string;objetivo:string;descricao:string;como:string[];importante:string;sinais:string[];erros:string[]};
const FASES:Fase[]=[
  {num:"01",titulo:"Adaptação ao Pombal",emoji:"🏠",cor:"#22C55E",duracao:"2–4 semanas",objetivo:"Criar vínculo, rotina e reconhecimento do ambiente",descricao:"Antes das solturas, a ave precisa reconhecer entrada, poleiro, rotina e tratador.",como:["Manter no pombal durante o período de adaptação","Associar o retorno a alimento, calma e segurança","Treinar resposta a um chamado consistente","Confirmar entrada tranquila antes de avançar","Manter rotina estável e manejo gentil"],importante:"Não avance apenas por calendário: observe o comportamento individual.",sinais:["Entra ao chamado","Reconhece o poleiro","Permanece calma com o tratador","Alimenta-se normalmente"],erros:["Soltar antes da adaptação","Mudar rotinas constantemente","Capturar de forma brusca"]},
  {num:"02",titulo:"Voos Livres ao Redor",emoji:"🔄",cor:"#3B82F6",duracao:"2–4 semanas",objetivo:"Conhecer a região e desenvolver condicionamento básico",descricao:"Voos livres graduais ajudam a formar referências visuais e capacidade física.",como:["Começar com períodos curtos supervisionados","Progredir gradualmente conforme recuperação","Preferir manhã cedo ou fim da tarde em clima adequado","Observar coesão do lote e retorno","Interromper se houver predadores ou clima inseguro"],importante:"Não force duração nem altitude; progresso depende de saúde, idade e confiança.",sinais:["Voa unido","Retorna ao chamado","Aumenta a duração sem fadiga","Evita pousos prolongados fora"],erros:["Forçar voo","Treinar em calor ou vento forte","Ignorar aves atrasadas"]},
  {num:"03",titulo:"Primeiras Solturas Curtas",emoji:"📍",cor:"#EAB308",duracao:"3–5 semanas",objetivo:"Introduzir orientação em distâncias seguras",descricao:"Comece perto e progrida apenas quando o grupo retornar bem e recuperar normalmente.",como:["1km em local seguro","3km após retornos consistentes","5km e 10km gradualmente","20km apenas com boa recuperação","30–50km para consolidação, se apropriado"],importante:"Aumente no máximo cerca de 30% por etapa e recue diante de atraso, estresse ou perda.",sinais:["Retorno no mesmo dia","Tempo melhora gradualmente","Apetite normal","Sem fadiga excessiva"],erros:["Saltar distâncias","Ignorar retardatários","Treinar aves doentes ou cansadas"]},
  {num:"04",titulo:"Orientação Progressiva",emoji:"🧭",cor:"#F97316",duracao:"4–8 semanas",objetivo:"Desenvolver autonomia em condições seguras",descricao:"Variações graduais ajudam a evitar dependência de uma única linha, sem expor as aves a risco desnecessário.",como:["Variar direção gradualmente","Variar pontos de soltura seguros","Usar apenas boa visibilidade e clima adequado","Alternar pequenos grupos e solturas individuais experientes","Registrar clima, retorno e recuperação"],importante:"Não treine em neblina, tempestade, calor extremo ou vento perigoso.",sinais:["Retorno consistente de direções treinadas","Saída tranquila da caixa","Boa recuperação","Menor dependência do bando"],erros:["Sempre a mesma linha","Mudar tudo ao mesmo tempo","Treinar em condições adversas"]},
  {num:"05",titulo:"Treino de Velocidade",emoji:"⚡",cor:"#EF4444",duracao:"Temporada",objetivo:"Trabalhar retorno eficiente em 100–300km",descricao:"Na velocidade, sessões curtas e recuperação adequada são mais úteis que excesso de distância.",como:["Distâncias de referência: 30–80km","Até 2–3 sessões semanais conforme recuperação","Pequenos grupos antes de individualizar","Soltura individual apenas para aves experientes","Registrar tempo e entrada no pombal"],importante:"A individualização deve ser gradual e nunca aplicada a aves inseguras ou sem base.",sinais:["Entrada rápida","Pouca circulação","Recuperação curta","Condição corporal adequada"],erros:["Volume excessivo","Individualizar cedo demais","Treinar cansado"]},
  {num:"06",titulo:"Treino de Meio Fundo",emoji:"🏃",cor:"#60A5FA",duracao:"Temporada",objetivo:"Construir ritmo e resistência para 300–700km",descricao:"O objetivo é consistência, economia de energia e recuperação entre sessões.",como:["Progredir de 100 para 300km conforme histórico","Alternar grupo e autonomia","Manter ritmo controlado","Frequência de referência: 1–2 vezes/semana","Ajustar ao clima e recuperação"],importante:"Treino longo só conta quando a recuperação também é boa.",sinais:["Ritmo estável","Boa condição na chegada","Recuperação em 48h","Apetite normal"],erros:["Excesso de grupo","Pouco descanso","Ignorar clima e condição"]},
  {num:"07",titulo:"Treino de Fundo Extremo",emoji:"🦅",cor:"#A78BFA",duracao:"Pré-temporada e temporada",objetivo:"Desenvolver resistência com máxima recuperação",descricao:"Em fundo, qualidade e descanso têm prioridade sobre frequência.",como:["Progressões longas somente com base consolidada","Após sessão longa, ampliar recuperação","Menor frequência que velocidade","Escolher clima, rota e horário seguros","Suspender diante de doença ou fadiga"],importante:"Uma sessão longa mal recuperada prejudica mais do que ajuda.",sinais:["Condição corporal estável","Asa leve","Recuperação consistente","Fezes e apetite normais"],erros:["Aumentar rápido","Pouco descanso","Treinar ave cansada","Alimentação inadequada"]},
];
const TRUQUES=[["🍽️","Reforço positivo ao retorno","Ofereça alimento e tranquilidade após a entrada para fortalecer a rotina."],["❤️","Motivação sem estresse","Use vínculos e rotina com cuidado, sem privação ou manejo agressivo."],["🌅","Ambiente tranquilo","Reduza ruído, sustos e presença de predadores."],["🚫","Nunca punir ao retornar","Captura brusca associa o pombal a medo e prejudica a entrada."],["⏰","Rotina consistente","Horários e sinais previsíveis aumentam confiança."]] as const;
const SINAIS=[["💥","Sai da caixa sem pânico","Parte com decisão após reconhecer o ambiente"],["📈","Ganha altitude com controle","Não demonstra desorientação"],["🎯","Retorno eficiente","Reduz desvios conforme aprende"],["🚫","Autonomia gradual","Não depende sempre de bandos desconhecidos"],["😌","Comportamento calmo","Confiança no pombal e no manejo"],["👁️","Atenção e vitalidade","Observa o ambiente sem prostração"]] as const;
const ERROS=[["📏","Aumentar distância rápido","Use progressões pequenas, próximas de 30%"],["🌡️","Treinar em calor extremo","Suspenda treino em calor intenso ou ave ofegante"],["😴","Soltar ave cansada","Aguarde recuperação completa"],["🤒","Treinar ave doente","Qualquer sinal clínico exige pausa e avaliação"],["🍽️","Alimentação inadequada","Evite excessos e mudanças bruscas antes da sessão"],["🔄","Sempre a mesma linha","Varie gradualmente sem mudar todas as condições juntas"],["👶","Começar sem maturidade","Inicie somente após adaptação e desenvolvimento adequados"]] as const;

export default function TreinamentoOrientacao(){
  const[faseSel,setFaseSel]=useState(0);const[tab,setTab]=useState<Tab>("fases");const fase=FASES[faseSel];
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}><Link href="/centro-provas" style={{...T.btnGhost,display:"inline-block",textDecoration:"none",marginBottom:16}}>← Voltar</Link>
    <header style={{padding:20,marginBottom:16,textAlign:"center",borderRadius:14,background:"linear-gradient(135deg,#052e16,#0a1628)",border:`2px solid ${T.green}`}}><div style={{fontSize:36}}>🧭</div><h1 style={{...T.h1,color:T.green,fontSize:22}}>Treinamento de Orientação</h1><p style={{...T.small,fontSize:13}}>Das primeiras solturas à competição<br/><b style={{color:T.green}}>Progressão, segurança e bem-estar</b></p></header>
    <nav style={{display:"flex",gap:5,marginBottom:16}}>{([['fases','🎯 Fases'],['truques','🏆 Práticas'],['sinais','👁️ Sinais'],['erros','⚠️ Erros']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:9,borderRadius:9,fontSize:11,fontWeight:800,color:tab===k?T.bg:T.dim,background:tab===k?T.green:T.bgCard,border:`1px solid ${tab===k?T.green:T.border}`}}>{l}</button>)}</nav>
    {tab==="fases"&&<><div style={{display:"flex",gap:4,overflowX:"auto",marginBottom:14}}>{FASES.map((f,i)=><button key={f.num} onClick={()=>setFaseSel(i)} style={{minWidth:72,padding:9,borderRadius:9,color:T.white,background:faseSel===i?f.cor:T.bgCard,border:`1px solid ${faseSel===i?f.cor:T.border}`}}><div>{f.emoji}</div><small>Fase {f.num}</small></button>)}</div><FaseCard fase={fase}/><div style={{display:"flex",gap:8}}>{faseSel>0&&<button onClick={()=>setFaseSel(faseSel-1)} style={{...T.btnGhost,flex:1}}>← Fase anterior</button>}{faseSel<FASES.length-1&&<button onClick={()=>setFaseSel(faseSel+1)} style={{...T.btn,flex:2}}>Próxima fase →</button>}</div></>}
    {tab==="truques"&&<><Intro emoji="🏆" title="Práticas Usadas por Bons Criadores" color={T.gold}/>{TRUQUES.map(([e,t,d])=><Card key={t} emoji={e} title={t} description={d} color={T.gold}/>)}<section style={{...T.card,border:`2px solid ${T.green}55`}}><Title color={T.green}>🧠 Reforço Positivo</Title><p style={{fontSize:13,lineHeight:1.8}}>O retorno deve ser associado a alimento, vínculo, rotina e ambiente seguro. Nunca use punição ou captura agressiva.</p><Info color={T.green}>🏆 A ave deve entrar voluntariamente e com confiança.</Info></section></>}
    {tab==="sinais"&&<><Intro emoji="👁️" title="Sinais de Boa Adaptação e Orientação" color={T.gold}/>{SINAIS.map(([e,t,d])=><Card key={t} emoji={e} title={t} description={d} color={T.gold}/>)}<section style={T.card}><Title color={T.gold}>📅 Quando começar</Title><div className="age-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Info color={T.green}>Jovens: somente após adaptação completa, voos livres consistentes e desenvolvimento adequado.</Info><Info color={T.blue}>Adultos: iniciar a pré-temporada com base já consolidada e avaliação individual.</Info></div></section></>}
    {tab==="erros"&&<><Intro emoji="⚠️" title="Erros que Comprometem Aves Jovens" color={T.red}/>{ERROS.map(([e,t,d])=><section key={t} style={{...T.card,borderLeft:`4px solid ${T.red}`}}><div style={{display:"flex",gap:11}}><span style={{fontSize:25}}>{e}</span><div><b style={{color:T.red}}>❌ {t}</b><div style={{color:T.green,fontSize:12,marginTop:4}}>✅ {d}</div></div></div></section>)}<section style={T.card}><Title color={T.gold}>📋 Semana de referência</Title>{[["Segunda","Descanso e avaliação",T.blue],["Terça","Treino curto, se recuperado",T.green],["Quarta","Treino médio conforme progressão",T.orange],["Quinta","Sessão principal ou descanso",T.red],["Sexta","Voo livre leve e observação",T.blue],["Sábado","Prova ou descanso planejado",T.gold]].map(([d,a,c])=><div key={d} style={{display:"flex",gap:12,padding:"8px 0",borderBottom:`1px solid ${T.border}`}}><b style={{color:c,minWidth:62,fontSize:12}}>{d}</b><span style={{fontSize:12}}>{a}</span></div>)}</section></>}
  </div><style jsx global>{`button{font-family:inherit;cursor:pointer}@media(max-width:520px){.phase-grid,.age-grid{grid-template-columns:1fr!important}}`}</style></main>
}
function FaseCard({fase}:{fase:Fase}){return <section style={{padding:16,marginBottom:12,borderRadius:14,background:`${fase.cor}0d`,border:`2px solid ${fase.cor}55`}}><div style={{display:"flex",gap:12,alignItems:"center"}}><span style={{width:50,height:50,display:"grid",placeItems:"center",borderRadius:12,fontSize:27,background:`${fase.cor}20`}}>{fase.emoji}</span><div><small style={{color:fase.cor}}>FASE {fase.num} • {fase.duracao}</small><h2 style={{margin:0,fontSize:18}}>{fase.titulo}</h2><div style={T.small}>{fase.objetivo}</div></div></div><p style={{padding:10,borderRadius:8,background:"#ffffff06",fontSize:13,lineHeight:1.7}}>{fase.descricao}</p><Title color={fase.cor}>📋 COMO FAZER</Title>{fase.como.map(v=><div key={v} style={{padding:"6px 9px",marginBottom:4,borderRadius:7,background:"#ffffff06",fontSize:12}}><span style={{color:fase.cor}}>→</span> {v}</div>)}<Info color={fase.cor}>⭐ {fase.importante}</Info><div className="phase-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:9}}><List title="✅ Sinais positivos" values={fase.sinais} color={T.green}/><List title="❌ Erros a evitar" values={fase.erros} color={T.red}/></div></section>}
function List({title,values,color}:{title:string;values:string[];color:string}){return <div style={{padding:10,borderRadius:8,background:`${color}0d`,border:`1px solid ${color}44`}}><b style={{color,fontSize:10}}>{title}</b>{values.map(v=><div key={v} style={{fontSize:11,paddingTop:3}}>• {v}</div>)}</div>}
function Intro({emoji,title,color}:{emoji:string;title:string;color:string}){return <section style={{...T.card,textAlign:"center",border:`2px solid ${color}55`}}><div style={{fontSize:32}}>{emoji}</div><b style={{color}}>{title}</b></section>}
function Card({emoji,title,description,color}:{emoji:string;title:string;description:string;color:string}){return <section style={{...T.card,borderLeft:`4px solid ${color}`}}><div style={{display:"flex",gap:12}}><span style={{fontSize:28}}>{emoji}</span><div><b style={{color}}>{title}</b><p style={{...T.small,fontSize:13,lineHeight:1.6,marginBottom:0}}>{description}</p></div></div></section>}
function Title({children,color}:{children:React.ReactNode;color:string}){return <div style={{fontSize:12,fontWeight:800,color,marginBottom:8}}>{children}</div>}
function Info({children,color}:{children:React.ReactNode;color:string}){return <div style={{padding:10,borderRadius:8,color,background:`${color}12`,border:`1px solid ${color}44`,fontSize:12,lineHeight:1.6}}>{children}</div>}
