"use client";

import { useCallback, useEffect, useState } from "react";
import { classificarProva, diasParaProva, loadCalendario, type ProvaCalendario } from "../data/calendario";
import { aplicarPombalSalvo } from "../lib/apis-gratis";
import { T } from "../theme";

type Tab = "agora" | "7dias" | "provas";
type DiaClima = { data:string; max:number; min:number; chuva:number; chuvaPct:number; vento:number; ventoDir:number; wmo:number };
type DadosClima = { cidade:string; temp:number; tempMax:number; tempMin:number; chuva:number; chuvaPct:number; vento:number; ventoDir:number; umidade:number; pressao:number; wmo:number; atualizado:string; previsao7:DiaClima[] };
const BASE="Pombal (sua base)";
const COORDS:Record<string,{lat:number;lon:number}>={
  [BASE]:{lat:-23.55,lon:-46.63},Cravinhos:{lat:-21.34,lon:-47.73},Jardinópolis:{lat:-21.02,lon:-47.77},"São Joaquim da Barra":{lat:-20.58,lon:-47.85},Igarapava:{lat:-20.03,lon:-47.76},Uberaba:{lat:-19.75,lon:-47.93},Araguari:{lat:-18.65,lon:-48.19},Catalão:{lat:-18.17,lon:-47.94},"Campo Alegre":{lat:-17.63,lon:-47.78},Cristalina:{lat:-16.77,lon:-47.61},Brasília:{lat:-15.78,lon:-47.93},
};
const DIRECOES=["Norte","Nordeste","Leste","Sudeste","Sul","Sudoeste","Oeste","Noroeste"];
function wmoInfo(code:number){if(code===0)return{desc:"Céu limpo",emoji:"☀️"};if(code<=2)return{desc:"Parcialmente nublado",emoji:"⛅"};if(code===3)return{desc:"Encoberto",emoji:"☁️"};if(code<=49)return{desc:"Névoa/neblina",emoji:"🌫️"};if(code<=59)return{desc:"Garoa",emoji:"🌦️"};if(code<=69)return{desc:"Chuva",emoji:"🌧️"};if(code<=79)return{desc:"Granizo/neve",emoji:"🌨️"};if(code<=86)return{desc:"Chuva forte",emoji:"⛈️"};if(code>=95)return{desc:"Tempestade",emoji:"⛈️"};return{desc:"Variável",emoji:"🌤️"}}
function direcao(deg:number){const d=["N","NNE","NE","ENE","L","ESE","SE","SSE","S","SSO","SO","OSO","O","ONO","NO","NNO"];return d[Math.round(deg/22.5)%16]}
function ventoAnalise(graus:number,pombal:string){const dirs=DIRECOES,iV=Math.round(graus/45)%8,iP=dirs.indexOf(pombal),emp=(iV+4)%8,ang=Math.min(Math.abs(emp-iP),8-Math.abs(emp-iP));if(ang===0)return{tipo:"Totalmente favorável",cor:T.green,emoji:"🟢"};if(ang<=1)return{tipo:"Favorável",cor:T.green,emoji:"🟢"};if(ang<=2)return{tipo:"Lateral",cor:"#FBBF24",emoji:"🟡"};if(ang<=3)return{tipo:"Parcial contra",cor:T.orange,emoji:"🟠"};return{tipo:"Vento contra",cor:T.red,emoji:"🔴"}}
function score(temp:number,chuva:number,vento:number,wmo:number){let p=100;if(temp>35)p-=30;else if(temp>30)p-=15;else if(temp<5)p-=25;else if(temp<10)p-=10;if(chuva>5)p-=40;else if(chuva>1)p-=20;else if(chuva>0)p-=5;if(vento>50)p-=30;else if(vento>30)p-=15;if(wmo>=95)p-=30;else if(wmo>=80)p-=15;p=Math.max(0,Math.min(100,p));if(p>=75)return{pts:p,label:"Ótimas condições",cor:T.green};if(p>=50)return{pts:p,label:"Condições razoáveis",cor:"#FBBF24"};if(p>=30)return{pts:p,label:"Condições difíceis",cor:T.orange};return{pts:p,label:"Condições ruins",cor:T.red}}
function alimento(temp:number,chuva:number,vento:number){if(chuva>2)return"Chuva: mantenha alimento seco, água limpa e observe o consumo.";if(temp>32)return`Calor (${temp}°C): mistura mais leve, água abundante e eletrólitos conforme protocolo.`;if(vento>30)return"Vento forte: revise a carga energética conforme distância e condição corporal.";if(temp<10)return`Frio (${temp}°C): ajuste gradual de energia e monitore peso e consumo.`;return"Condições adequadas: mantenha a mistura padrão da categoria."}
async function buscar(cidade:string,lat:number,lon:number):Promise<DadosClima>{const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),current:"temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m,wind_direction_10m,pressure_msl",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,wind_speed_10m_max,wind_direction_10m_dominant",timezone:"America/Sao_Paulo",forecast_days:"7",wind_speed_unit:"kmh",precipitation_unit:"mm"});const r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),c=j.current,d=j.daily;if(!c||!d)throw new Error("Resposta climática inválida");return{cidade,temp:Math.round(c.temperature_2m),tempMax:Math.round(d.temperature_2m_max[0]),tempMin:Math.round(d.temperature_2m_min[0]),chuva:c.precipitation,chuvaPct:d.precipitation_probability_max[0],vento:Math.round(c.wind_speed_10m),ventoDir:c.wind_direction_10m,umidade:c.relative_humidity_2m,pressao:Math.round(Number(c.pressure_msl??0))||0,wmo:c.weather_code,atualizado:new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),previsao7:d.time.map((dt:string,i:number)=>({data:dt,max:Math.round(d.temperature_2m_max[i]),min:Math.round(d.temperature_2m_min[i]),chuva:d.precipitation_sum[i],chuvaPct:d.precipitation_probability_max[i],vento:Math.round(d.wind_speed_10m_max[i]),ventoDir:d.wind_direction_10m_dominant[i],wmo:d.weather_code[i]}))}}
function fmtData(dt:string){return new Date(`${dt}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"short",day:"numeric",month:"short"})}

export default function PrevisaoTempo(){
  const[provas,setProvas]=useState<ProvaCalendario[]>([]);const[cidade,setCidade]=useState(BASE);const[pombalDir,setPombalDir]=useState("Sul");const[dados,setDados]=useState<DadosClima|null>(null);const[loading,setLoading]=useState(false);const[erro,setErro]=useState("");const[tab,setTab]=useState<Tab>("agora");
  useEffect(()=>setProvas(loadCalendario()),[]);
  useEffect(()=>{const p=aplicarPombalSalvo();COORDS[BASE]={lat:p.lat,lon:p.lon}},[]);
  const hoje=new Date().toISOString().slice(0,10),proxima=provas.find(p=>p.dataSolta>=hoje&&!p.cancelada);
  const consultar=useCallback(async(c:string)=>{const coord=COORDS[c];if(!coord){setDados(null);setErro("Ainda não há coordenadas cadastradas para esta cidade.");return}setLoading(true);setErro("");try{setDados(await buscar(c,coord.lat,coord.lon))}catch(e){setDados(null);setErro(`Não foi possível obter dados reais agora. ${e instanceof Error?e.message:"Erro de rede"}`)}finally{setLoading(false)}},[]);
  useEffect(()=>{consultar(cidade)},[cidade,consultar]);
  const info=dados?wmoInfo(dados.wmo):null,sc=dados?score(dados.temp,dados.chuva,dados.vento,dados.wmo):null,va=dados?ventoAnalise(dados.ventoDir,pombalDir):null;
  const cidades=[BASE,...provas.map(p=>p.cidade).filter((v,i,a)=>a.indexOf(v)===i)];
  return <div><div style={{marginBottom:16}}><h1 style={T.h1}>📡 Previsão do Tempo</h1><p style={{...T.small,marginTop:4}}>Dados reais • Open-Meteo • Direção e velocidade do vento</p></div>
    <section style={T.card}><Title>📍 Selecionar local</Title><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:10}}>{cidades.map(c=>{const p=provas.find(x=>x.cidade===c),prox=p?.num===proxima?.num;return <button key={c} onClick={()=>setCidade(c)} style={{padding:"7px 10px",borderRadius:20,fontSize:10,fontWeight:800,color:cidade===c?T.bg:prox?T.gold:T.dim,background:cidade===c?T.gold:prox?`${T.gold}15`:T.bgInput,border:`1px solid ${cidade===c?T.gold:prox?T.gold:T.border}`}}>{c===BASE?"🏠 Pombal":p?`#${p.num} ${c.split(" ")[0]}${prox?" ⭐":""}`:c}</button>})}</div><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={T.small}>Pombal fica ao:</span><select value={pombalDir} onChange={e=>setPombalDir(e.target.value)} style={{...T.input,flex:1}}>{DIRECOES.map(d=><option key={d}>{d}</option>)}</select><button onClick={()=>consultar(cidade)} style={T.btnSm}>🔄</button></div></section>
    {loading&&<div style={{textAlign:"center",padding:30,color:T.dim}}>⏳ Buscando dados climáticos reais...</div>}{erro&&<div style={{padding:12,marginBottom:12,borderRadius:9,color:T.red,background:`${T.red}12`,border:`1px solid ${T.red}44`}}>⚠️ {erro}<button onClick={()=>consultar(cidade)} style={{...T.btnSm,marginLeft:10}}>Tentar novamente</button></div>}
    {dados&&!loading&&<><nav style={{display:"flex",gap:6,marginBottom:12}}>{([['agora','🌡️ Agora'],['7dias','📅 7 Dias'],['provas','🏁 Provas']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:10,borderRadius:9,fontWeight:800,color:tab===k?T.bg:T.dim,background:tab===k?T.gold:T.bgCard,border:`1px solid ${tab===k?T.gold:T.border}`}}>{l}</button>)}</nav>
      {tab==="agora"&&info&&sc&&va&&<><section style={{...T.card,borderColor:`${T.gold}55`,background:`${T.gold}0d`}}><div style={{display:"flex",justifyContent:"space-between"}}><div><small style={{color:T.gold}}>{dados.cidade.toUpperCase()} • {dados.atualizado}</small><div style={{fontSize:48}}>{info.emoji}</div><b>{info.desc}</b></div><div style={{textAlign:"right"}}><div style={{fontSize:54,color:T.gold,fontWeight:900}}>{dados.temp}°</div><small>↑{dados.tempMax}° ↓{dados.tempMin}°</small></div></div><div style={{padding:10,marginTop:13,borderRadius:9,color:sc.cor,background:`${sc.cor}12`,border:`1px solid ${sc.cor}55`}}><b>● {sc.label}</b><strong style={{float:"right"}}>{sc.pts}%</strong><div style={{height:5,marginTop:7,background:"#ffffff14"}}><div style={{height:"100%",width:`${sc.pts}%`,background:sc.cor}}/></div><small>Score climático estimado para avaliação de prova</small></div></section><div className="weather-metrics" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}>{[["💧","Umidade",`${dados.umidade}%`],["🌧️","Chuva",`${dados.chuva.toFixed(1)}mm (${dados.chuvaPct}%)`],["💨","Velocidade do vento",`${dados.vento}km/h`],["🧭","Direção do vento",direcao(dados.ventoDir)],["🌡️","Pressão",dados.pressao>0?`${dados.pressao} hPa`:"—"]].map(([e,l,v])=><Metric key={l} emoji={e} label={l} value={v}/>)}</div><section style={T.card}><Title>💨 Análise do Vento para Prova</Title><div style={{padding:13,borderRadius:9,color:va.cor,background:`${va.cor}12`,border:`1px solid ${va.cor}55`}}><h3 style={{margin:"0 0 5px"}}>{va.emoji} {va.tipo}</h3><div style={T.small}>Vento vindo de {direcao(dados.ventoDir)} a {dados.vento}km/h. A análise depende da direção aproximada selecionada para o pombal.</div><div style={{display:"flex",justifyContent:"space-around",textAlign:"center",marginTop:12}}><div><small>VENTO VEM DE</small><div style={{fontSize:24}}>💨</div><b style={{color:T.blue}}>{direcao(dados.ventoDir)}</b></div><div style={{alignSelf:"center"}}>→</div><div><small>POMBAL AO</small><div style={{fontSize:24}}>🏠</div><b style={{color:T.gold}}>{pombalDir}</b></div></div></div></section><section style={T.card}><Title>🌾 Alimentação Recomendada</Title><div style={{padding:10,borderRadius:8,background:"#ffffff08",color:T.dim,fontSize:13}}>{alimento(dados.temp,dados.chuva,dados.vento)}</div></section></>}
      {tab==="7dias"&&<section style={T.card}><Title>📅 Previsão 7 dias — {dados.cidade}</Title>{dados.previsao7.map((d,i)=>{const wi=wmoInfo(d.wmo),ds=score(d.max,d.chuva,d.vento,d.wmo),v=ventoAnalise(d.ventoDir,pombalDir),p=provas.find(x=>x.dataSolta===d.data);return <div key={d.data} style={{padding:"11px 0",borderBottom:`1px solid ${T.border}`}}><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{fontSize:22}}>{wi.emoji}</span><div style={{flex:1}}><b>{fmtData(d.data)} {i===0&&<small style={{color:T.gold}}>Hoje</small>}</b>{p&&<span style={{marginLeft:6,padding:"2px 7px",borderRadius:10,color:T.bg,background:T.gold,fontSize:9}}>🏁 #{p.num} {p.cidade}</span>}<div style={T.small}>🌡️ {d.min}°–{d.max}° • 🌧️ {d.chuvaPct}% • 💨 {d.vento}km/h {direcao(d.ventoDir)}</div><div style={{display:"flex",gap:7,marginTop:5}}><div style={{height:4,flex:1,background:"#ffffff14"}}><div style={{height:"100%",width:`${ds.pts}%`,background:ds.cor}}/></div><small style={{color:ds.cor}}>{ds.pts}%</small><small style={{color:v.cor}}>{v.emoji} {v.tipo}</small></div></div></div></div>})}<p style={{...T.small,textAlign:"center"}}>Fonte: Open‑Meteo</p></section>}
      {tab==="provas"&&<div><div style={{...T.small,padding:9,marginBottom:10,color:T.blue,background:`${T.blue}12`,borderRadius:8}}>Selecione uma prova para consultar o clima real da cidade.</div>{provas.map(p=>{const d=diasParaProva(p.dataSolta),c=classificarProva(p.km),selected=cidade===p.cidade;return <button key={p.id||p.num} onClick={()=>{setCidade(p.cidade);setTab("agora")}} style={{width:"100%",padding:13,marginBottom:7,borderRadius:10,textAlign:"left",color:T.white,background:selected?`${c.cor}15`:T.bgCard,border:`1px solid ${selected?c.cor:T.border}`,borderLeft:`4px solid ${d<0?T.green:c.cor}`,opacity:d<0?.65:1}}><b>#{p.num} {p.cidade} — {p.estado}</b><span style={{float:"right",color:T.blue}}>Ver →</span><div style={{...T.small,marginTop:4}}>{c.emoji} {c.tipo} • {p.km}km • {p.dataSolta} {d<0?"• Realizada":`• ${d}d`}</div></button>})}</div>}
    </>}
    <style jsx global>{`button,select{font-family:inherit}select option{background:${T.bgInput}}@media(max-width:520px){.weather-metrics{grid-template-columns:1fr 1fr!important}}`}</style>
  </div>
}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:10}}>{children}</div>}
function Metric({emoji,label,value}:{emoji:string;label:string;value:string}){return <div style={{...T.card,margin:0,padding:12}}><div style={{fontSize:20}}>{emoji}</div><div style={T.small}>{label}</div><b style={{color:T.gold}}>{value}</b></div>}
