"use client";

import { useState } from "react";
import Link from "next/link";
import {
  CATEGORIAS, DOENCAS, RECOMENDACOES_GERAIS, CONSTANTES,
  VITAMINAS, MINERAIS, AMINOACIDOS, QUIMIOTERAPICOS, ANTIPARASITARIOS,
  type Doenca
} from "../data/tratamentos";
import { T } from "../theme";

type Tab = "doencas" | "geral" | "busca" | "vitaminas" | "medicamentos";
const CORES:Record<string,string>={baixa:"#4ADE80",media:"#FBBF24",alta:"#F97316",critica:"#EF4444"};
const LABELS:Record<string,string>={baixa:"🟢 Baixa",media:"🟡 Média",alta:"🟠 Alta",critica:"🔴 CRÍTICA"};

export default function GuiaTerapeutico(){
  const [cat,setCat]=useState("Todas");
  const [query,setQuery]=useState("");
  const [sel,setSel]=useState<Doenca|null>(null);
  const [tab,setTab]=useState<Tab>("doencas");
  const filtradas=DOENCAS.filter(d=>(cat==="Todas"||d.categoria===cat)&&(!query||[d.nome,d.agente,...d.sinais,...d.principios.map(p=>p.nome),d.categoria].some(v=>v.toLowerCase().includes(query.toLowerCase()))));

  if(sel)return <Shell><button onClick={()=>setSel(null)} style={{...T.btnGhost,marginBottom:16}}>← Voltar</button>
    <section style={{...T.card,border:`2px solid ${sel.cor}66`,background:`${sel.cor}0d`}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><small style={{color:sel.cor}}>{sel.categoria.toUpperCase()}</small><h1 style={{...T.h1,marginTop:5}}>{sel.emoji} {sel.nome}</h1></div><Urgencia value={sel.urgencia}/></div></section>
    {sel.zoonose&&<div style={{padding:"10px 13px",marginBottom:10,borderRadius:9,color:T.red,background:"#ef444418",border:"1px solid #ef444444",fontSize:12,fontWeight:800}}>🚨 ZOONOSE — pode contagiar o homem! Use luvas e máscara.</div>}
    <section style={T.card}><Title>🦠 Agente Causal</Title><p style={{color:T.dim,fontSize:13}}>{sel.agente}</p></section>
    <section style={T.card}><Title>📡 Transmissão</Title><p style={{color:T.dim,fontSize:13,lineHeight:1.6}}>{sel.transmissao}</p></section>
    <section style={T.card}><Title>🔍 Sinais Clínicos / Sintomas</Title>{sel.sinais.map(s=><div key={s} style={{padding:"6px 0",borderBottom:`1px solid ${T.border}`,fontSize:12,color:T.dim,lineHeight:1.5}}><span style={{color:sel.cor}}>•</span> {s}</div>)}</section>
    <section style={T.card}><Title>🔬 Diagnóstico</Title><p style={{color:T.dim,fontSize:13}}>{sel.diagnostico}</p></section>
    <section style={T.card}><Title>💊 Princípios Ativos e Orientação</Title>{sel.principios.map(p=><div key={p.nome} style={{padding:13,marginBottom:10,borderRadius:11,background:"#ffffff06",border:`1px solid ${T.border}`,borderLeft:`4px solid ${sel.cor}`}}><b>{p.nome}</b><div className="dose-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><Info label="💉 Dose" value={p.dose} color={T.gold}/><Info label="⏱️ Duração" value={p.duracao} color={T.blue}/></div>{p.obs&&<div style={{padding:8,marginTop:8,borderRadius:8,color:p.obs.includes("⚠️")||p.obs.includes("🚨")?T.red:T.dim,background:"#ffffff05",fontSize:12,lineHeight:1.5}}>{p.obs}</div>}</div>)}</section>
    <section style={T.card}><Title>🛡️ Profilaxia / Prevenção</Title>{sel.profilaxia.map(p=><div key={p} style={{padding:"5px 0",borderBottom:`1px solid ${T.border}`,fontSize:12,color:T.dim}}>✅ {p}</div>)}</section>
    {sel.imunidade&&<section style={T.card}><Title>🧬 Imunidade</Title><p style={{color:T.blue,fontSize:13}}>{sel.imunidade}</p></section>}
    <section style={T.card}><Title>📋 Recomendações de Manejo</Title>{sel.recomendacoes.map(r=><div key={r} style={{padding:"6px 0",borderBottom:`1px solid ${T.border}`,fontSize:13,color:r.startsWith("🚨")?T.red:r.startsWith("⚠️")?"#FBBF24":T.dim,lineHeight:1.5}}>{r.startsWith("🚨")||r.startsWith("⚠️")?r:`• ${r}`}</div>)}</section>
    <Disclaimer/></Shell>;

  return <Shell><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><div><h1 style={T.h1}>🏥 Guia Terapêutico</h1><p style={{...T.small,marginTop:4}}>Doenças, sinais clínicos, vitaminas e medicamentos para pombos</p></div><Link href="/centro-provas" style={{...T.btnGhost,textDecoration:"none"}}>← Centro</Link></div>
    <section style={{...T.card,marginBottom:10,borderLeft:`4px solid ${T.blue}`}}><Title>📊 Constantes Fisiológicas do Pombo</Title><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}><MiniBox label="🌡️ Temperatura" value={CONSTANTES.temperatura}/><MiniBox label="⚖️ Peso Médio" value={CONSTANTES.pesoMedio}/><MiniBox label="💧 Água/dia" value={CONSTANTES.aguaPorDia}/><MiniBox label="🌾 Alimento/dia" value={CONSTANTES.alimentoPorDia}/></div></section>
    <Disclaimer/>
    <nav style={{display:"flex",gap:4,margin:"14px 0",flexWrap:"wrap"}}>{([['doencas','🦠 Doenças'],['geral','📋 Recomendações'],['vitaminas','💊 Vitaminas'],['medicamentos','💉 Medicamentos'],['busca','🔍 Buscar']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,minWidth:60,padding:9,borderRadius:10,cursor:"pointer",fontSize:11,fontWeight:800,color:tab===k?T.bg:T.dim,background:tab===k?T.gold:T.bgCard,border:`1px solid ${tab===k?T.gold:T.border}`}}>{l}</button>)}</nav>

    {tab==="busca"&&<><section style={T.card}><input placeholder="🔍 Buscar doença, sintoma, agente ou princípio..." value={query} onChange={e=>setQuery(e.target.value)} style={T.input}/></section>{query?filtradas.map(d=><Card key={d.id} d={d} onClick={()=>setSel(d)}/>):<Empty/>}{query&&!filtradas.length&&<p style={{textAlign:"center",color:T.dim}}>Nenhum resultado para "{query}".</p>}</>}

    {tab==="doencas"&&<><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:12}}>{CATEGORIAS.map(c=><button key={c} onClick={()=>setCat(c)} style={{padding:"6px 11px",borderRadius:20,cursor:"pointer",fontSize:11,fontWeight:700,color:cat===c?T.bg:T.dim,background:cat===c?T.gold:T.bgInput,border:`1px solid ${cat===c?T.gold:T.border}`}}>{c}</button>)}</div><div className="urg-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:14}}>{Object.keys(CORES).map(u=><div key={u} style={{padding:10,borderRadius:9,display:"flex",justifyContent:"space-between",color:CORES[u],background:`${CORES[u]}10`,border:`1px solid ${CORES[u]}44`}}><b>{LABELS[u]}</b><strong>{DOENCAS.filter(d=>d.urgencia===u).length}</strong></div>)}</div>{filtradas.map(d=><Card key={d.id} d={d} onClick={()=>setSel(d)}/>)}</>}

    {tab==="geral"&&<>{RECOMENDACOES_GERAIS.map(r=><section key={r.titulo} style={{...T.card,borderLeft:`4px solid ${r.urgente?T.red:T.gold}`,background:r.urgente?"#ef44440f":T.bgCard}}><b style={{color:r.urgente?T.red:T.gold}}>{r.titulo}</b><p style={{...T.small,fontSize:13,lineHeight:1.7}}>{r.desc}</p></section>)}</>}

    {tab==="vitaminas"&&<><section style={T.card}><Title>💊 Vitaminas — Necessidades diárias por pombo</Title><p style={{...T.small,marginBottom:10,color:T.dim}}>É praticamente impossível produzir hipervitaminose — o excesso é metabolizado e eliminado. Devem ser fornecidas periodicamente. Vitaminas do complexo B oxidam-se rapidamente — NÃO deixar nos bebedouros de um dia para o outro. A carência de uma vitamina B = fornecer o COMPLEXO B inteiro.</p></section>{VITAMINAS.map(v=><section key={v.nome} style={{...T.card,borderLeft:`3px solid ${T.gold}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b style={{color:T.gold}}>{v.nome}</b><span style={{padding:"3px 8px",borderRadius:12,fontSize:10,fontWeight:800,color:T.blue,background:`${T.blue}15`}}>{v.necessidade}</span></div><div style={{marginTop:6}}><span style={{fontSize:11,color:T.dim,fontWeight:700}}>Ação:</span><p style={{...T.small,lineHeight:1.5}}>{v.acao}</p></div><div style={{marginTop:4}}><span style={{fontSize:11,color:T.red,fontWeight:700}}>Carência:</span><p style={{...T.small,lineHeight:1.5,color:"#FBBF24"}}>{v.carencia}</p></div></section>)}
    <section style={T.card}><Title>🧲 Minerais</Title><p style={{...T.small,marginBottom:8,color:T.dim}}>Substâncias indispensáveis. As aves regulam a ingestão de complexos minerais de acordo com suas necessidades.</p>{MINERAIS.map(m=><div key={m.nome} style={{padding:"7px 0",borderBottom:`1px solid ${T.border}`,fontSize:12}}><b style={{color:T.blue}}>{m.nome}</b><div style={{color:T.dim}}>{m.acao}</div></div>)}</section>
    <section style={T.card}><Title>🧬 Aminoácidos Essenciais</Title><p style={{...T.small,marginBottom:8,color:T.dim}}>Aminoácidos que o organismo NÃO sintetiza em quantidades adequadas — devem estar na dieta.</p>{AMINOACIDOS.map(a=><div key={a.nome} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:`1px solid ${T.border}`,fontSize:12}}><span>{a.nome}</span><b style={{color:T.gold}}>{a.necessidade}</b></div>)}</section></>}

    {tab==="medicamentos"&&<><section style={T.card}><Title>💉 Quimioterápicos — Anti-infecciosos</Title><p style={{...T.small,marginBottom:10,color:T.dim}}>⚠️ Todos exigem prescrição e acompanhamento veterinário. A dose muda conforme peso, diagnóstico e concentração do produto.</p>{Array.from(new Set(QUIMIOTERAPICOS.map(q=>q.classe))).map(classe=><div key={classe} style={{marginBottom:14}}><div style={{fontSize:11,fontWeight:800,color:T.blue,marginBottom:6,textTransform:"uppercase",letterSpacing:1}}>{classe}</div>{QUIMIOTERAPICOS.filter(q=>q.classe===classe).map(q=><div key={q.nome} style={{padding:10,marginBottom:6,borderRadius:9,background:"#ffffff06",borderLeft:`3px solid ${T.gold}`}}><b style={{fontSize:12}}>{q.nome}</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,marginTop:6}}><MiniBox label="Ação" value={q.acao}/><MiniBox label="Dose" value={q.dose}/></div>{q.toxicidade&&<div style={{marginTop:4,fontSize:11,color:q.toxicidade.includes("⚠️")?T.red:T.dim,lineHeight:1.4}}>{q.toxicidade.includes("⚠️")?"⚠️":""} {q.toxicidade.replace("⚠️","")}</div>}</div>)}</div>)}</section>
    <section style={T.card}><Title>🪱 Antiparasitários</Title>{Array.from(new Set(ANTIPARASITARIOS.map(a=>a.classe))).map(classe=><div key={classe} style={{marginBottom:14}}><div style={{fontSize:11,fontWeight:800,color:"#a78bfa",marginBottom:6,textTransform:"uppercase",letterSpacing:1}}>{classe}</div>{ANTIPARASITARIOS.filter(a=>a.classe===classe).map(a=><div key={a.nome} style={{padding:10,marginBottom:6,borderRadius:9,background:"#ffffff06",borderLeft:`3px solid #a78bfa`}}><b style={{fontSize:12}}>{a.nome}</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:4,marginTop:6}}><MiniBox label="Ação" value={a.acao}/><MiniBox label="Dose" value={a.dose}/></div>{a.toxicidade&&a.toxicidade!=="—"&&<div style={{marginTop:4,fontSize:11,color:a.toxicidade.includes("⚠️")?T.red:T.dim,lineHeight:1.4}}>{a.toxicidade.includes("⚠️")?"⚠️":""} {a.toxicidade.replace("⚠️","")}</div>}</div>)}</div>)}</section></>}

  </Shell>
}

function Card({d,onClick}:{d:Doenca;onClick:()=>void}){return <button onClick={onClick} style={{width:"100%",textAlign:"left",padding:14,marginBottom:8,borderRadius:11,cursor:"pointer",color:T.white,background:T.bgCard,border:`1px solid ${d.cor}44`,borderLeft:`4px solid ${d.cor}`}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div style={{flex:1}}><b>{d.emoji} {d.nome}</b><div><span style={{fontSize:10,color:d.cor}}>{d.categoria}</span>{d.zoonose&&<span style={{fontSize:10,color:T.red,marginLeft:8}}>🚨 ZOONOSE</span>}</div><div style={{...T.small,marginTop:5,lineHeight:1.4}}>{d.sinais[0].substring(0,80)}...</div></div><div><Urgencia value={d.urgencia}/><small style={{display:"block",color:T.dim,textAlign:"center",marginTop:4}}>{d.principios.length} princípio(s)</small></div></div></button>}
function Urgencia({value}:{value:string}){return <span style={{display:"inline-block",padding:"4px 9px",borderRadius:20,fontSize:10,fontWeight:800,color:CORES[value],background:`${CORES[value]}18`,border:`1px solid ${CORES[value]}44`}}>{LABELS[value]}</span>}
function Disclaimer(){return <div style={{padding:"11px 13px",margin:"12px 0",borderRadius:9,color:T.blue,background:"#60a5fa12",border:`1px solid ${T.blue}44`,fontSize:12,lineHeight:1.6}}>ℹ️ <b>Guia informativo baseado em referência columbófila. Não substitui diagnóstico veterinário.</b> Consulte um médico-veterinário antes de administrar medicamentos. Dificuldade respiratória, sinais neurológicos, trauma grave ou mortalidade súbita são emergências.</div>}
function Info({label,value,color}:{label:string;value:string;color:string}){return <div style={{padding:8,borderRadius:8,background:`${color}10`}}><div style={T.small}>{label}</div><b style={{fontSize:12,color}}>{value}</b></div>}
function MiniBox({label,value}:{label:string;value:string}){return <div style={{padding:5,borderRadius:6,background:"#ffffff05"}}><div style={{fontSize:9,color:T.dim}}>{label}</div><div style={{fontSize:11,fontWeight:700}}>{value}</div></div>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:10}}>{children}</div>}
function Empty(){return <div style={{textAlign:"center",padding:32,color:T.dim}}><div style={{fontSize:32}}>🔍</div><p>Digite um sintoma, doença ou princípio ativo.</p></div>}
function Shell({children}:{children:React.ReactNode}){return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>{children}</div><style jsx global>{`button,input{font-family:inherit}@media(max-width:520px){.dose-grid{grid-template-columns:1fr!important}.urg-grid{grid-template-columns:1fr 1fr!important}}`}</style></main>}
