import type { CSSProperties } from "react";

export const T = {
  bg: "#0b1426",
  bgCard: "#1b283c",
  bgInput: "#0b1529",
  border: "#31415a",
  gold: "#f7bd00",
  goldDark: "#ca8a04",
  green: "#39e58c",
  blue: "#55a3ff",
  red: "#ff5d62",
  white: "#f8fafc",
  dim: "#9aa8bc",
  dim2: "#64748b",
  orange: "#f97316",
  btn: {
    boxSizing: "border-box",
    width: "100%",
    padding: "12px 16px",
    color: "#0b1426",
    background: "#f7bd00",
    border: "1px solid #f7bd00",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  } satisfies CSSProperties,
  btnGhost: {
    padding: "8px 13px",
    color: "#f8fafc",
    background: "#1b283c",
    border: "1px solid #31415a",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  btnSm: {
    padding: "8px 11px",
    color: "#0b1426",
    background: "#f7bd00",
    border: "1px solid #f7bd00",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  } satisfies CSSProperties,
  btnDanger: {
    padding: "8px 11px",
    color: "#fecaca",
    background: "rgba(239,68,68,.12)",
    border: "1px solid rgba(239,68,68,.4)",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  } satisfies CSSProperties,
  h1: {
    color: "#f8fafc",
    fontSize: 24,
    lineHeight: 1.2,
    fontWeight: 800,
    margin: 0,
  } satisfies CSSProperties,
  small: {
    color: "#9aa8bc",
    fontSize: 12,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  label: {
    color: "#9aa8bc",
    fontSize: 10,
    lineHeight: 1.2,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  } satisfies CSSProperties,
  card: {
    background: "#1b283c",
    border: "1px solid #31415a",
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  } satisfies CSSProperties,
  input: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: 42,
    padding: "9px 12px",
    color: "#f8fafc",
    background: "#0b1529",
    border: "1px solid #31415a",
    borderRadius: 8,
    outline: "none",
  } satisfies CSSProperties,
} as const;
