"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { T } from "../theme";

type Treino={id:string;data:string;distancia:number;local:string;tempoMin:number;clima:string;observacoes:string};
type Form={data:string;distancia:number;local:string;horas:number;minutos:number;segundos:number;clima:string;observacoes:string};
const KEY="nutripombos-treinos-v1";
const CLIMAS=["Ensolarado","Nublado","Chuvoso","Vento leve","Vento forte","Frio","Quente"];
const vazio=():Form=>({data:new Date().toISOString().slice(0,10),distancia:50,local:"",horas:0,minutos:45,segundos:0,clima:"Ensolarado",observacoes:""});
function read():Treino[]{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function paraForm(t:Treino):Form{const total=Math.round(t.tempoMin*60);return{data:t.data,distancia:t.distancia,local:t.local,horas:Math.floor(total/3600),minutos:Math.floor(total%3600/60),segundos:total%60,clima:t.clima,observacoes:t.observacoes}}
function totalSeg(f:Form){return Math.max(0,f.horas*3600+f.minutos*60+f.segundos)}
function hms(seg:number){return[Math.floor(seg/3600),Math.floor(seg%3600/60),seg%60].map(v=>String(v).padStart(2,"0")).join(":")}

export default function Treinamentos(){
  const[treinos,setTreinos]=useState<Treino[]>([]);const[ready,setReady]=useState(false);const[show,setShow]=useState(false);const[editId,setEditId]=useState<string|null>(null);const[form,setForm]=useState<Form>(vazio());
  useEffect(()=>{setTreinos(read());setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(treinos))},[treinos,ready]);
  const segundos=totalSeg(form),horas=segundos/3600,velKmh=horas>0?form.distancia/horas:0,velMmin=segundos>0?form.distancia*1000/(segundos/60):0;
  const totalKm=treinos.reduce((s,t)=>s+t.distancia,0),maior=treinos.length?Math.max(...treinos.map(t=>t.distancia)):0,media=treinos.length?Math.round(totalKm/treinos.length):0;
  function abrir(t?:Treino){setForm(t?paraForm(t):vazio());setEditId(t?.id||null);setShow(true)}
  function salvar(){if(!form.local.trim()){alert("Informe o local.");return}if(segundos<=0){alert("Informe uma duração válida.");return}const dados={data:form.data,distancia:form.distancia,local:form.local,tempoMin:segundos/60,clima:form.clima,observacoes:form.observacoes};setTreinos(v=>(editId?v.map(t=>t.id===editId?{...t,...dados}:t):[...v,{id:crypto.randomUUID(),...dados}]).sort((a,b)=>a.data.localeCompare(b.data)));setShow(false);setEditId(null)}
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10,marginBottom:20}}><div><Link href="/centro-provas" style={{...T.small,textDecoration:"none"}}>← Centro de Provas</Link><h1 style={{...T.h1,marginTop:9}}>🏋️ Treinamentos</h1><p style={{...T.small,marginTop:4}}>Histórico, duração e evolução dos treinos</p></div><button onClick={()=>abrir()} style={T.btnSm}>+ Treino</button></div>
    <div className="training-stats" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:12}}>{[["Treinos",treinos.length],["Km totais",`${totalKm}km`],["Maior dist.",`${maior}km`]].map(([l,v])=><div key={l} style={{...T.card,margin:0,padding:11,textAlign:"center"}}><div style={T.small}>{l}</div><b style={{display:"block",fontSize:20,color:T.gold,marginTop:4}}>{v}</b></div>)}</div>
    {treinos.length>0&&<div style={{...T.small,marginBottom:12,textAlign:"right"}}>Distância média: {media}km</div>}
    {show&&<section style={T.card}><Title>{editId?"✏️ Editar Treino":"➕ Novo Treino"}</Title><div className="training-form-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Field label="📅 Data"><input type="date" value={form.data} onChange={e=>setForm(v=>({...v,data:e.target.value}))} style={T.input}/></Field><Field label="📏 Distância (km)"><input type="number" min={1} value={form.distancia} onChange={e=>setForm(v=>({...v,distancia:+e.target.value}))} style={T.input}/></Field></div><Field label="📍 Local *"><input value={form.local} onChange={e=>setForm(v=>({...v,local:e.target.value}))} placeholder="Ex.: Varginha" style={T.input}/></Field><div style={{...T.label,marginBottom:5}}>⏱️ Duração (HH:MM:SS)</div><div className="duration-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:10}}>{[["HH","horas",form.horas],["MM","minutos",form.minutos],["SS","segundos",form.segundos]].map(([l,k,v])=><label key={k}><small style={{color:T.dim}}>{l}</small><input type="number" min={0} max={k==="horas"?99:59} value={v} onChange={e=>setForm(p=>({...p,[k]:+e.target.value}))} style={{...T.input,textAlign:"center",fontSize:18,fontWeight:800}}/></label>)}</div>{segundos>0&&<div style={{padding:9,marginBottom:10,borderRadius:8,color:T.green,background:`${T.green}12`}}>⏱️ {hms(segundos)} • ⚡ {velKmh.toFixed(1)}km/h • {Math.round(velMmin).toLocaleString("pt-BR")}m/min</div>}<Field label="🌤️ Clima"><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{CLIMAS.map(c=><button key={c} onClick={()=>setForm(v=>({...v,clima:c}))} style={{padding:"7px 10px",borderRadius:20,fontSize:11,color:form.clima===c?T.bg:T.dim,background:form.clima===c?T.gold:T.bgInput,border:`1px solid ${form.clima===c?T.gold:T.border}`}}>{c}</button>)}</div></Field><Field label="📝 Observações"><textarea rows={3} value={form.observacoes} onChange={e=>setForm(v=>({...v,observacoes:e.target.value}))} placeholder="Condições, comportamento e recuperação..." style={{...T.input,height:80}}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>{setShow(false);setEditId(null)}} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvar} style={{...T.btn,flex:2}}>💾 Salvar</button></div></section>}
    {[...treinos].reverse().map(t=>{const seg=Math.round(t.tempoMin*60),kmh=t.tempoMin>0?t.distancia/(t.tempoMin/60):0,mmin=t.tempoMin>0?t.distancia*1000/t.tempoMin:0;return <section key={t.id} style={T.card}><div style={{display:"flex",justifyContent:"space-between",gap:9}}><div><b>{t.local}</b><div style={{...T.small,marginTop:3}}>{t.data} • {t.clima}</div><div style={{display:"flex",gap:11,flexWrap:"wrap",marginTop:5}}><b style={{color:T.gold}}>{t.distancia}km</b><span style={T.small}>⏱️ {hms(seg)}</span><b style={{color:T.green,fontSize:12}}>⚡ {kmh.toFixed(1)}km/h • {Math.round(mmin)}m/min</b></div>{t.observacoes&&<p style={{...T.small,fontStyle:"italic"}}>{t.observacoes}</p>}</div><div style={{display:"flex",gap:5}}><button onClick={()=>abrir(t)} style={T.btnGhost}>✏️</button><button onClick={()=>{if(confirm("Excluir treino?"))setTreinos(v=>v.filter(x=>x.id!==t.id))}} style={T.btnDanger}>🗑️</button></div></div><div style={{height:4,marginTop:9,borderRadius:3,background:"#ffffff14"}}><div style={{height:"100%",width:`${Math.min(100,t.distancia/500*100)}%`,background:T.gold}}/></div></section>})}{ready&&!treinos.length&&<div style={{padding:32,textAlign:"center",color:T.dim}}>Nenhum treino registrado.</div>}
  </div><style jsx global>{`button,input,textarea{font-family:inherit}button{cursor:pointer}@media(max-width:520px){.training-form-grid{grid-template-columns:1fr!important}.duration-grid{grid-template-columns:repeat(3,1fr)!important}.training-stats{grid-template-columns:repeat(3,1fr)!important}}`}</style></main>
}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:11}}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:11}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
