"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { T } from "../theme";

type Tab = "trat" | "farm";
type Tratamento = { id:string; tipo:string; produto:string; data:string; proxima:string; obs:string };
type Medicamento = { id:string; produto:string; quantidade:number; validade:string };
const TRAT_KEY="nutripombos-tratamentos-v1";
const FARM_KEY="nutripombos-farmacia-v1";
const hojeISO=()=>new Date().toISOString().slice(0,10);
function read<T>(key:string):T[]{try{const value=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(value)?value:[]}catch{return[]}}
function diferencaDias(data:string){if(!data)return null;const alvo=new Date(`${data}T12:00:00`).getTime(),hoje=new Date(`${hojeISO()}T12:00:00`).getTime();return Math.ceil((alvo-hoje)/86400000)}

export default function ControleSanitario(){
  const[tab,setTab]=useState<Tab>("trat");const[tratamentos,setTratamentos]=useState<Tratamento[]>([]);const[farmacia,setFarmacia]=useState<Medicamento[]>([]);const[ready,setReady]=useState(false);const[showTrat,setShowTrat]=useState(false);const[showFarm,setShowFarm]=useState(false);const[editTrat,setEditTrat]=useState<string|null>(null);const[editFarm,setEditFarm]=useState<string|null>(null);const[formT,setFormT]=useState({tipo:"Vacina",produto:"",data:hojeISO(),proxima:"",obs:""});const[formF,setFormF]=useState({produto:"",quantidade:1,validade:""});
  useEffect(()=>{setTratamentos(read(TRAT_KEY));setFarmacia(read(FARM_KEY));setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(TRAT_KEY,JSON.stringify(tratamentos))},[tratamentos,ready]);
  useEffect(()=>{if(ready)localStorage.setItem(FARM_KEY,JSON.stringify(farmacia))},[farmacia,ready]);
  const abrirTrat=(t?:Tratamento)=>{setFormT(t?{tipo:t.tipo,produto:t.produto,data:t.data,proxima:t.proxima,obs:t.obs}:{tipo:"Vacina",produto:"",data:hojeISO(),proxima:"",obs:""});setEditTrat(t?.id||null);setShowTrat(true)};
  const abrirFarm=(f?:Medicamento)=>{setFormF(f?{produto:f.produto,quantidade:f.quantidade,validade:f.validade}:{produto:"",quantidade:1,validade:""});setEditFarm(f?.id||null);setShowFarm(true)};
  const salvarTrat=()=>{if(!formT.produto.trim()){alert("Informe o produto, exame ou procedimento.");return}if(editTrat)setTratamentos(v=>v.map(t=>t.id===editTrat?{...t,...formT}:t));else setTratamentos(v=>[...v,{id:crypto.randomUUID(),...formT}]);setShowTrat(false);setEditTrat(null)};
  const salvarFarm=()=>{if(!formF.produto.trim()){alert("Informe o produto.");return}if(editFarm)setFarmacia(v=>v.map(f=>f.id===editFarm?{...f,...formF}:f));else setFarmacia(v=>[...v,{id:crypto.randomUUID(),...formF}]);setShowFarm(false);setEditFarm(null)};
  const alertasFarm=farmacia.filter(f=>{const d=diferencaDias(f.validade);return d!==null&&d<90});
  const alertasTrat=tratamentos.filter(t=>{const d=diferencaDias(t.proxima);return d!==null&&d<30});

  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10,marginBottom:18}}><div><h1 style={T.h1}>💉 Controle Sanitário</h1><p style={{...T.small,marginTop:4}}>Vacinas, tratamentos, exames e farmácia</p></div><Link href="/centro-provas" style={{...T.btnGhost,textDecoration:"none"}}>← Centro</Link></div>
    <div style={{padding:"10px 13px",marginBottom:12,borderRadius:9,color:T.blue,background:`${T.blue}12`,border:`1px solid ${T.blue}44`,fontSize:11,lineHeight:1.6}}>ℹ️ Este módulo registra condutas já definidas. Não administre medicamentos sem diagnóstico e orientação veterinária. Produtos vencidos devem ser separados e descartados corretamente.</div>
    {(alertasFarm.length>0||alertasTrat.length>0)&&<section style={{...T.card,borderColor:`${T.red}55`,background:`${T.red}0d`}}><Title color={T.red}>⚠️ Alertas</Title>{alertasFarm.map(f=>{const d=diferencaDias(f.validade)!;return <div key={f.id} style={{padding:"3px 0",fontSize:12,color:d<0?T.red:"#FBBF24"}}>• <b>{f.produto}</b> {d<0?`vencido há ${Math.abs(d)} dias`:d===0?"vence hoje":`vence em ${d} dias`}</div>})}{alertasTrat.map(t=>{const d=diferencaDias(t.proxima)!;return <div key={t.id} style={{padding:"3px 0",fontSize:12,color:d<0?T.red:"#FBBF24"}}>• <b>{t.produto}</b>: {d<0?`revisão atrasada há ${Math.abs(d)} dias`:d===0?"revisão hoje":`revisão em ${d} dias`}</div>})}</section>}
    <nav style={{display:"flex",gap:6,marginBottom:16}}><button onClick={()=>setTab("trat")} style={tabStyle(tab==="trat")}>💉 Registros Sanitários</button><button onClick={()=>setTab("farm")} style={tabStyle(tab==="farm")}>💊 Farmácia</button></nav>
    {tab==="trat"&&<><button onClick={()=>abrirTrat()} style={{...T.btn,marginBottom:12}}>+ Registrar Procedimento</button>{showTrat&&<section style={T.card}><Title>{editTrat?"✏️ Editar Registro":"➕ Novo Registro"}</Title><Field label="Tipo"><select value={formT.tipo} onChange={e=>setFormT(v=>({...v,tipo:e.target.value}))} style={T.input}>{["Vacina","Vermifugação","Tratamento","Exame","Consulta","Outro"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Produto, exame ou procedimento *"><input value={formT.produto} onChange={e=>setFormT(v=>({...v,produto:e.target.value}))} placeholder="Ex.: vacina, exame de fezes, consulta..." style={T.input}/></Field><div className="san-date-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Field label="Data"><input type="date" value={formT.data} onChange={e=>setFormT(v=>({...v,data:e.target.value}))} style={T.input}/></Field><Field label="Próxima revisão/dose"><input type="date" value={formT.proxima} onChange={e=>setFormT(v=>({...v,proxima:e.target.value}))} style={T.input}/></Field></div><Field label="Observações"><textarea rows={3} value={formT.obs} onChange={e=>setFormT(v=>({...v,obs:e.target.value}))} style={{...T.input,height:80}}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>{setShowTrat(false);setEditTrat(null)}} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvarTrat} style={{...T.btn,flex:2}}>💾 Salvar</button></div></section>}{tratamentos.map(t=><section key={t.id} style={T.card}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><Tag>{t.tipo}</Tag><b>{t.produto}</b></div><div style={{...T.small,marginTop:5}}>📅 {t.data}{t.proxima?` → próxima: ${t.proxima}`:""}</div>{t.obs&&<div style={{...T.small,fontStyle:"italic",marginTop:4}}>{t.obs}</div>}</div><div style={{display:"flex",gap:5}}><button onClick={()=>abrirTrat(t)} style={T.btnGhost}>✏️</button><button onClick={()=>{if(confirm("Excluir registro?"))setTratamentos(v=>v.filter(x=>x.id!==t.id))}} style={T.btnDanger}>🗑️</button></div></div></section>)}{ready&&!tratamentos.length&&<Empty text="Nenhum procedimento registrado"/>}</>}
    {tab==="farm"&&<><button onClick={()=>abrirFarm()} style={{...T.btn,marginBottom:12}}>+ Adicionar Produto</button>{showFarm&&<section style={T.card}><Title>{editFarm?"✏️ Editar Produto":"➕ Novo Produto"}</Title><Field label="Produto *"><input value={formF.produto} onChange={e=>setFormF(v=>({...v,produto:e.target.value}))} placeholder="Nome e concentração" style={T.input}/></Field><Field label="Quantidade"><input type="number" min={0} value={formF.quantidade} onChange={e=>setFormF(v=>({...v,quantidade:+e.target.value}))} style={T.input}/></Field><Field label="Validade"><input type="date" value={formF.validade} onChange={e=>setFormF(v=>({...v,validade:e.target.value}))} style={T.input}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>{setShowFarm(false);setEditFarm(null)}} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvarFarm} style={{...T.btn,flex:2}}>💾 Salvar</button></div></section>}<div style={{display:"grid",gap:8}}>{farmacia.map(f=>{const d=diferencaDias(f.validade),cor=d===null?T.dim:d<0?T.red:d<30?"#FBBF24":T.green;return <section key={f.id} style={{...T.card,margin:0,borderLeft:`4px solid ${cor}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><b>{f.produto}</b><div style={T.small}>Validade: {f.validade||"não informada"}</div><small style={{color:cor}}>{d===null?"Sem validade cadastrada":d<0?`VENCIDO há ${Math.abs(d)} dias`:d===0?"Vence hoje":`${d} dias até o vencimento`}</small></div><div style={{textAlign:"right"}}><strong style={{color:T.gold,fontSize:19}}>{f.quantidade} un</strong><div style={{display:"flex",gap:5,marginTop:6}}><button onClick={()=>abrirFarm(f)} style={T.btnGhost}>✏️</button><button onClick={()=>{if(confirm("Excluir produto?"))setFarmacia(v=>v.filter(x=>x.id!==f.id))}} style={T.btnDanger}>🗑️</button></div></div></div></section>})}</div>{ready&&!farmacia.length&&<Empty text="Farmácia vazia"/>}</>}
  </div><style jsx global>{`button,input,select,textarea{font-family:inherit}button{cursor:pointer}select option{background:${T.bgInput}}@media(max-width:520px){.san-date-grid{grid-template-columns:1fr!important}}`}</style></main>
}
function tabStyle(active:boolean){return{flex:1,padding:10,borderRadius:10,fontSize:13,fontWeight:active?800:500,color:active?T.bg:T.dim,background:active?T.gold:T.bgCard,border:`1px solid ${active?T.gold:T.border}`}}
function Title({children,color=T.gold}:{children:React.ReactNode;color?:string}){return <div style={{fontSize:13,fontWeight:800,color,marginBottom:11}}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:11}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
function Tag({children}:{children:React.ReactNode}){return <span style={{padding:"2px 7px",borderRadius:20,color:T.gold,background:`${T.gold}18`,fontSize:10}}>{children}</span>}
function Empty({text}:{text:string}){return <div style={{padding:25,textAlign:"center",color:T.dim}}>{text}</div>}
