"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { loadConfig } from "../config";
import { T } from "../theme";

type Aba = "protocolo" | "mistura" | "segredos";
type Dia = { dia:string; emoji:string; titulo:string; cor:string; objetivo:string; itens:{icon:string;txt:string}[]; alim:string; mix:string; dica:string; destaque?:boolean };
const itens=(values:string[][])=>values.map(([icon,txt])=>({icon,txt}));
const PROTOCOLO:Dia[]=[
  {dia:"Domingo",emoji:"💙",titulo:"Recuperação Total",cor:"#1E40AF",objetivo:"Recuperar depois da prova",itens:itens([["🛁","Banho obrigatório — hidratação da pele e penas"],["⚡","Eletrólitos + glicose na água"],["🌾","Mistura leve: cevada 50% + trigo 30% + arroz 20%"],["😴","Máximo repouso — sem treino"],["💊","Suporte nutricional conforme orientação profissional"]]),alim:"Cevada depurativa + eletrólitos. O pombo precisa expulsar toxinas.",mix:"2g/pombo — mínimo necessário",dica:"A recuperação do meio fundo leva 48-72h. Não apresse!"},
  {dia:"Segunda",emoji:"🟢",titulo:"Recuperação + Reconstrução",cor:"#166534",objetivo:"Reconstrução muscular e intestinal",itens:itens([["🏃","Voo livre 30 minutos — sem forçar"],["💪","Aminoácidos para reconstrução muscular"],["🦠","Probiótico na ração"],["🌾","Mistura equilibrada — mais proteína"],["💧","Muita água fresca disponível"]]),alim:"Milho 35% + Trigo 25% + Sorgo 20% + Ervilha 15% + Arroz 5%",mix:"3g/pombo — reconstrução",dica:"O intestino saudável é o motor do meio fundista."},
  {dia:"Terça",emoji:"🟡",titulo:"Reconstrução + Resistência Leve",cor:"#854D0E",objetivo:"Retomar condicionamento gradualmente",itens:itens([["📏","Soltura 30–60 km — ritmo constante"],["🎯","Objetivo: ritmo, não velocidade"],["💪","Suporte de aminoácidos e vitaminas"],["🕐","Registrar tempo de retorno"],["🌡️","Só treinar com clima favorável"]]),alim:"Milho 40% + Trigo 20% + Sorgo 20% + Arroz 10% + Girassol 10%",mix:"3g/pombo — pré-esforço",dica:"No meio fundo, ritmo constante supera velocidade bruta.",destaque:true},
  {dia:"Quarta",emoji:"🔵",titulo:"Treino de Resistência",cor:"#1E3A5F",objetivo:"Construir capacidade aeróbica",itens:itens([["📏","Soltura 80–150 km — ritmo constante"],["⏱️","Voo de 45-60 minutos antes da soltura"],["🫁","Fortalecer pulmão e cardiovascular"],["💧","Eletrólitos pós-treino"],["📊","Registrar condições e tempo de retorno"]]),alim:"Milho 40% + Sorgo 20% + Trigo 15% + Arroz c/casca 10% + Girassol 10% + Ervilha 5%",mix:"3,5g/pombo — suporte aeróbico",dica:"Este é o treino mais importante do meio fundista."},
  {dia:"Quinta",emoji:"🟠",titulo:"Carga Energética",cor:"#9A3412",objetivo:"Acumular energia para a prova",itens:itens([["🌾","Mistura energética — mais milho e girassol"],["⚗️","Mix Final — 7g/pombo"],["⚡","Eletrólitos"],["😌","Descanso — sem treino intenso"],["💊","Suporte antioxidante e aminoácidos"]]),alim:"Milho 40% + Sorgo 20% + Trigo 15% + Girassol 15% + Arroz c/casca 10%",mix:"7g/pombo — DOSE PRINCIPAL MEIO FUNDO",dica:"Oleaginosas liberam energia lentamente.",destaque:true},
  {dia:"Sexta",emoji:"🟣",titulo:"Equilíbrio Leve + Hidratação",cor:"#4C1D95",objetivo:"Manter equilíbrio sem desgastar",itens:itens([["💧","Hidratação reforçada"],["🏃","Voo livre leve 20–30 minutos"],["🌾","Mistura leve"],["❤️","Viuvez breve, se utilizada"],["✅","Verificar condição física individual"]]),alim:"Milho 40% + Trigo 30% + Sorgo 20% + Arroz 10%",mix:"2g/pombo — leve pré-enceste",dica:"Qualquer pombo fora do padrão não deve ser encestado."},
  {dia:"Sábado",emoji:"⭐",titulo:"Encestamento / PROVA",cor:"#065F46",objetivo:"Enceste na condição ideal",itens:itens([["🌅","Manhã: ração leve"],["💧","Água com eletrólitos"],["👁️","Verificar peito, penas e olhar"],["❤️","Motivação breve"],["🏁","Enceste tranquilo e seguro"]]),alim:"Milho miúdo 50% + Trigo 30% + Sorgo 20% — levíssimo",mix:"Sem Mix — encestamento",dica:"Peito musculoso sem gordura, penas sedosas e olhar concentrado."},
];
const GRAOS=[["Milho",40,"#EAB308","Carboidrato principal"],["Sorgo",20,"#F97316","Digestão rápida + leve"],["Trigo",15,"#3B82F6","Proteína moderada + B"],["Arroz c/casca",10,"#22C55E","Digestão suave"],["Girassol",10,"#A78BFA","Gordura boa + energia longa"],["Ervilha",5,"#EF4444","Proteína muscular"]] as const;
const MIX=[["Aveia",300,"#EAB308","Energia de liberação lenta"],["Amido de batata",200,"#3B82F6","Carboidrato rápido"],["Proteína de soja",120,"#22C55E","Proteína vegetal"],["Levedura de cerveja",80,"#A78BFA","Vitaminas B + flora"],["Beterraba (pó)",70,"#EF4444","Circulação"],["Spirulina",50,"#06B6D4","Proteína + antioxidante"],["Espinafre (pó)",40,"#22C55E","Ferro"],["Linhaça (pó)",30,"#F97316","Ômega 3"],["Beta-alanina",8,"#F472B6","Suporte ao esforço"],["Creatina",5,"#FBBF24","Reserva muscular"],["Alho (pó)",15,"#94A3B8","Suporte imunológico"]] as const;
const SEGREDOS=[["🫁","Recuperação perfeita","Quem recupera bem entre provas ganha mais do que quem apenas treina mais."],["🦠","Intestino saudável","Flora intestinal equilibrada favorece a absorção."],["💧","Hidratação constante","Reponha fluidos depois de treinos e provas."],["⚡","Reserva energética","O rendimento depende da reserva disponível no dia."],["😴","Descanso correto","Recuperação planejada faz parte do treino."]] as const;

export default function MeioFundo(){
  const[tab,setTab]=useState<Aba>("protocolo");const[diaSel,setDiaSel]=useState(0);const[pombos,setPombos]=useState(30);
  useEffect(()=>setPombos(loadConfig().quantidadePombos),[]);
  const dia=PROTOCOLO[diaSel],total=MIX.reduce((s,m)=>s+m[1],0);
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}><Link href="/centro-provas" style={{...T.btnGhost,display:"inline-block",textDecoration:"none",marginBottom:16}}>← Voltar</Link>
    <header style={{padding:20,textAlign:"center",borderRadius:14,marginBottom:16,background:"linear-gradient(135deg,#1E3A5F,#0a1628)",border:`2px solid ${T.blue}`}}><div style={{fontSize:36}}>🏃</div><h1 style={{...T.h1,color:T.blue,fontSize:24}}>Meio Fundo</h1><p style={{...T.small,fontSize:13}}>300–700 km • Equilíbrio entre potência e resistência<br/><b style={{color:T.blue}}>Ritmo constante supera velocidade bruta</b></p><div style={{display:"flex",gap:8,justifyContent:"center",flexWrap:"wrap"}}>{["Potência","Resistência","Ritmo","Estabilidade"].map(v=><span key={v} style={{padding:"4px 11px",borderRadius:20,fontSize:10,color:T.blue,background:"#3b82f633"}}>✓ {v}</span>)}</div></header>
    <nav style={{display:"flex",gap:5,marginBottom:16}}>{([['protocolo','📅 Protocolo'],['mistura','🌾 Mistura'],['segredos','🏆 Segredos']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={{flex:1,padding:10,borderRadius:10,cursor:"pointer",fontSize:12,fontWeight:800,color:tab===k?T.white:T.dim,background:tab===k?T.blue:T.bgCard,border:`1px solid ${tab===k?T.blue:T.border}`}}>{l}</button>)}</nav>
    {tab==="protocolo"&&<><div style={{display:"flex",gap:4,overflowX:"auto",marginBottom:14}}>{PROTOCOLO.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{minWidth:70,padding:9,borderRadius:9,cursor:"pointer",color:T.white,background:diaSel===i?d.cor:T.bgCard,border:`1px solid ${diaSel===i?d.cor:T.border}`}}><div>{d.emoji}</div><small>{d.dia.slice(0,3)}</small></button>)}</div><DiaCard dia={dia}/><section style={T.card}><Title>📋 Semana Completa</Title>{PROTOCOLO.map((d,i)=><button key={d.dia} onClick={()=>setDiaSel(i)} style={{width:"100%",display:"flex",gap:9,alignItems:"center",padding:9,marginBottom:5,borderRadius:8,textAlign:"left",cursor:"pointer",color:T.white,background:diaSel===i?`${d.cor}20`:"#ffffff05",border:`1px solid ${diaSel===i?d.cor:T.border}`}}><span>{d.emoji}</span><b>{d.dia}</b><span style={{...T.small,flex:1}}>{d.titulo}</span>{d.destaque&&<span>⭐</span>}</button>)}</section></>}
    {tab==="mistura"&&<><section style={{...T.card,borderColor:`${T.blue}55`}}><h2 style={{color:T.blue,fontSize:15}}>🌾 Mistura Base de Grãos</h2><p style={T.small}>Equilíbrio entre carboidrato e gordura boa.</p><Bar items={GRAOS.map(v=>({value:v[1],color:v[2]}))}/>{GRAOS.map(([n,p,c,o])=><Ingrediente key={n} nome={n} valor={`${p}%`} cor={c} obs={o}/>)}</section><section style={T.card}><h2 style={{color:"#A78BFA",fontSize:15}}>⚗️ Fórmula Mix Meio Fundo</h2><p style={T.small}>Dose: <b>7g/pombo</b> — quinta-feira</p><Bar items={MIX.map(v=>({value:v[1],color:v[2]}))}/>{MIX.map(([n,g,c,o])=><Ingrediente key={n} nome={n} valor={`${g}g • ${(g/total*100).toFixed(1)}%`} cor={c} obs={o}/>)}<Info color="#A78BFA">⚗️ Total da fórmula: {total}g</Info></section><section style={T.card}><Title>🧮 Calculadora</Title><input type="number" min={1} value={pombos} onChange={e=>setPombos(+e.target.value)} style={{...T.input,textAlign:"center",fontSize:20,fontWeight:900,marginBottom:10}}/><div className="mf-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[["Mix Final/semana",`${(pombos*.007).toFixed(2)}kg`,"#A78BFA"],["Grãos/dia",`${(pombos*.03).toFixed(2)}kg`,T.gold],["Água/dia",`${Math.ceil(pombos/20)}L`,T.blue],["Custo mix/semana",`R$${(pombos*7*.055).toFixed(2)}`,T.green]].map(([l,v,c])=><Metric key={l} label={l} value={v} color={c}/>)}</div></section></>}
    {tab==="segredos"&&<><section style={{...T.card,textAlign:"center",border:`2px solid ${T.blue}66`}}><div style={{fontSize:32}}>🏆</div><b style={{color:T.blue}}>Segredos dos Campeões de Meio Fundo</b></section>{SEGREDOS.map(([e,t,d])=><section key={t} style={{...T.card,borderLeft:`4px solid ${T.blue}`,display:"flex",gap:12}}><span style={{fontSize:28}}>{e}</span><div><b style={{color:T.blue}}>{t}</b><p style={{...T.small,fontSize:13}}>{d}</p></div></section>)}<section style={{...T.card,border:`2px solid ${T.blue}66`}}><Title>⚖️ O Ponto Ideal do Meio Fundista</Title><p style={{fontSize:13,lineHeight:1.9}}><span style={{color:T.red}}>❌ Não pode estar gordo</span><br/><span style={{color:T.red}}>❌ Não pode estar magro</span><br/><br/><b style={{color:T.blue}}>✅ Precisa estar ELÁSTICO:</b><br/>• Musculatura firme e leve<br/>• Asa deslizante<br/>• Recuperação rápida<br/>• Intestino funcionando perfeitamente</p><Info color={T.blue}>🎯 Esse é o ponto ideal do campeão de meio fundo.</Info></section></>}
  </div><style jsx global>{`button,input{font-family:inherit}@media(max-width:520px){.mf-grid{grid-template-columns:1fr 1fr!important}}`}</style></main>
}
function DiaCard({dia}:{dia:Dia}){return <section style={{padding:16,marginBottom:12,borderRadius:14,background:`${dia.cor}20`,border:`2px solid ${dia.cor}66`}}><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:12}}><span style={{fontSize:36}}>{dia.emoji}</span><div><small style={{color:T.blue}}>{dia.dia.toUpperCase()}</small><h2 style={{margin:0,fontSize:20}}>{dia.titulo}</h2><div style={T.small}>{dia.objetivo}</div></div></div>{dia.itens.map(v=><div key={v.txt} style={{display:"flex",gap:9,padding:"8px 10px",marginBottom:5,borderRadius:8,background:"#ffffff08",fontSize:13}}><span>{v.icon}</span>{v.txt}</div>)}<Info color={T.blue}>🌾 <b>ALIMENTAÇÃO:</b> {dia.alim}</Info><Info color="#A78BFA">⚗️ <b>MIX FINAL:</b> {dia.mix}</Info><Info color={dia.destaque?T.blue:T.dim}>{dia.destaque?"⭐ DICA FUNDAMENTAL":"💡 DICA"}: {dia.dica}</Info></section>}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.blue,marginBottom:10}}>{children}</div>}
function Info({children,color}:{children:React.ReactNode;color:string}){return <div style={{padding:"9px 11px",marginTop:8,borderRadius:8,color,background:`${color}12`,border:`1px solid ${color}44`,fontSize:12}}>{children}</div>}
function Bar({items}:{items:{value:number;color:string}[]}){return <div style={{display:"flex",height:13,borderRadius:7,overflow:"hidden",margin:"12px 0"}}>{items.map((v,i)=><div key={i} style={{flex:v.value,background:v.color}}/>)}</div>}
function Ingrediente({nome,valor,cor,obs}:{nome:string;valor:string;cor:string;obs:string}){return <div style={{padding:"7px 0",borderBottom:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between"}}><b style={{fontSize:12}}><span style={{color:cor}}>●</span> {nome}</b><b style={{color:cor}}>{valor}</b></div><div style={{...T.small,fontSize:10}}>{obs}</div></div>}
function Metric({label,value,color}:{label:string;value:string;color:string}){return <div style={{padding:10,textAlign:"center",borderRadius:8,background:`${color}12`,border:`1px solid ${color}44`}}><div style={T.small}>{label}</div><b style={{color}}>{value}</b></div>}
