import { Bird, Check, Crown, ShieldCheck, Sparkles, Zap } from "lucide-react";
import Link from "next/link";

const plans = [
  { name:"Anual", price:"297", suffix:"/ano", description:"Para quem prefere começar com menor investimento.", icon:Zap, color:"text-blue-300", border:"border-blue-300/20", button:"bg-white/10 text-white", features:["Todos os módulos","Atualizações durante a assinatura","Suporte por email","1 usuário e 1 pombal"] },
  { name:"Vitalício Fundador", price:"497", suffix:"pagamento único", description:"Oferta de lançamento para os primeiros clientes.", icon:Crown, color:"text-amber-300", border:"border-amber-300/45", button:"bg-gradient-to-r from-amber-300 to-amber-400 text-slate-950", featured:true, features:["Acesso vitalício à versão adquirida","Todos os módulos atuais","12 meses de atualizações","Suporte prioritário por 12 meses","Selo de cliente fundador"] },
  { name:"Vitalício Oficial", price:"797", suffix:"pagamento único", description:"Preço oficial após o período de lançamento.", icon:Sparkles, color:"text-emerald-300", border:"border-emerald-300/20", button:"bg-emerald-400 text-slate-950", features:["Acesso vitalício à versão adquirida","Todos os módulos atuais","12 meses de atualizações","1 usuário e 1 pombal","Suporte por email"] },
];

export default function PlanosPage(){return <main className="min-h-screen bg-[#07101f] text-white"><header className="border-b border-white/[.07]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><Link href="/" className="flex items-center gap-3 text-white no-underline"><span className="grid size-10 place-items-center rounded-xl bg-emerald-400 text-slate-950"><Bird size={21}/></span><b>Nutri Pombos</b></Link><Link href="/login" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-bold text-slate-300 no-underline hover:text-white">Já sou cliente</Link></div></header>
  <section className="mx-auto max-w-7xl px-5 py-16 text-center md:px-8 md:py-24"><div className="mx-auto max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-amber-300/15 bg-amber-300/[.06] px-3 py-2 text-[10px] font-extrabold uppercase tracking-[.16em] text-amber-300"><ShieldCheck size={13}/> Investimento no seu plantel</span><h1 className="mt-6 text-5xl font-semibold tracking-[-.055em] md:text-7xl">Escolha como entrar<br/><span className="text-emerald-300">na nova geração.</span></h1><p className="mx-auto mt-6 max-w-2xl text-sm leading-7 text-slate-400 md:text-base">Comece com sete dias gratuitos. Depois, escolha o formato que melhor combina com seu pombal.</p></div>
    <div className="mt-14 grid gap-5 text-left lg:grid-cols-3">{plans.map(({name,price,suffix,description,icon:Icon,color,border,button,featured,features})=><article key={name} className={`relative rounded-[1.7rem] border ${border} bg-white/[.032] p-6 ${featured?"shadow-[0_25px_80px_rgba(245,158,11,.1)]":""}`}>{featured&&<span className="absolute -top-3 left-6 rounded-full bg-amber-300 px-3 py-1 text-[9px] font-black uppercase tracking-[.12em] text-slate-950">Melhor oferta</span>}<Icon size={24} className={color}/><h2 className="mt-5 text-lg font-bold">{name}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-slate-500">{description}</p><div className="my-7"><span className="text-sm text-slate-500">R$</span><strong className={`ml-2 text-5xl tracking-[-.05em] ${color}`}>{price}</strong><span className="ml-2 text-[10px] text-slate-500">{suffix}</span></div><ul className="space-y-3">{features.map(v=><li key={v} className="flex items-start gap-2.5 text-xs text-slate-400"><Check size={15} className={`mt-0.5 shrink-0 ${color}`}/>{v}</li>)}</ul><Link href="/cadastro" className={`mt-8 flex h-12 items-center justify-center rounded-xl text-xs font-extrabold no-underline transition hover:-translate-y-0.5 ${button}`}>Começar teste gratuito</Link></article>)}</div>
    <div className="mx-auto mt-10 max-w-3xl rounded-2xl border border-white/[.07] bg-white/[.025] p-5 text-left"><h3 className="text-sm font-bold">O que significa “vitalício”?</h3><p className="mt-2 text-xs leading-6 text-slate-500">Acesso permanente à versão adquirida. Serviços externos que gerem custo recorrente — como IA paga, WhatsApp ou armazenamento adicional — podem ser oferecidos separadamente. Essa definição protege a sustentabilidade do negócio.</p></div>
  </section></main>}
