"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { T } from "../theme";

type Receita = { id:string; nome:string; categoria:string; ingredientes:string[]; preparo:string };
type Form = Omit<Receita,"id">;
const KEY="nutripombos-receitas-v2";
const CATS=["Recuperação","Eletrólitos","Pré-prova","Respiratório","Personalizada"];
const CORES:Record<string,string>={Recuperação:"#3B82F6",Eletrólitos:"#06B6D4","Pré-prova":"#EAB308",Respiratório:"#22C55E",Personalizada:"#A78BFA"};

const SEED:Receita[]=[
  {id:"seed-1",nome:"Mistura Velocidade (10kg)",categoria:"Pré-prova",ingredientes:["4kg milho pequeno","2,5kg trigo","2kg sorgo","1kg ervilha","0,5kg girassol"],preparo:"Misture bem todos os grãos em recipiente limpo e seco.\n\n⚗️ Mix Final: 2g/pombo na quinta-feira.\n\nOfereça 30g/pombo/dia. Ajuste conforme consumo, clima e condição corporal. Em dias quentes, reduza o girassol. Armazene em local seco e ventilado."},
  {id:"seed-2",nome:"Mistura Meio Fundo (10kg)",categoria:"Pré-prova",ingredientes:["3kg milho","2kg ervilha","1,5kg trigo","1,5kg girassol","1kg sorgo","0,5kg amendoim","0,5kg linhaça"],preparo:"Misture os grãos uniformemente. A linhaça e o amendoim aumentam a densidade energética.\n\n⚗️ Mix Final: 3g/pombo conforme protocolo.\n\nTransição gradual: comece substituindo 25% da mistura anterior por dia até chegar a 100%. Ofereça 30g/pombo/dia."},
  {id:"seed-3",nome:"Mistura Fundo Extremo (10kg)",categoria:"Pré-prova",ingredientes:["2,5kg milho","2kg ervilha","1,5kg girassol","1kg trigo","1kg amendoim","0,5kg sorgo","0,5kg linhaça","0,5kg cânhamo","0,5kg açafrão"],preparo:"Mistura de alta energia para provas acima de 800km. O cânhamo e açafrão são fontes de gordura de qualidade.\n\n⚗️ Mix Final: 3g/pombo no protocolo de fundo.\n\nInicie a transição 5 dias antes da prova. Aumente a oferta de gordura progressivamente. Hidratação reforçada 48h antes."},
  {id:"seed-4",nome:"Mistura Depurativa (10kg)",categoria:"Recuperação",ingredientes:["4kg trigo","2kg sorgo","1,5kg milho","1,5kg aveia","1kg cevada"],preparo:"Mistura leve e fácil digestão, ideal para o dia após a prova ou período de descanso.\n\nOfereça 25g/pombo/dia por 2-3 dias após a prova.\n\nA aveia e a cevada ajudam a limpar o trato digestivo. Não use em período de treinamento intenso. Retorne à mistura de categoria quando o pombo estiver recuperado."},
  {id:"seed-5",nome:"Mistura de Recuperação Pós-Prova (5kg)",categoria:"Recuperação",ingredientes:["2kg milho","1kg ervilha","0,5kg girassol","0,5kg arroz","0,5kg linhaça","0,5kg açafrão"],preparo:"Para as primeiras 24-48h após a chegada da prova.\n\nO arroz (cozido ou em grão) é fácil de digerir. A linhaça e o açafrão ajudam na recuperação energética.\n\nOfereça 25-30g/pombo. Garanta água limpa e fresca. Observe se o pombo está comendo e digerindo normalmente. Se houver regurgitação ou apatia, isole e procure veterinário."},
  {id:"seed-6",nome:"Eletrólitos Caseiros (1 litro)",categoria:"Eletrólitos",ingredientes:["1 litro de água filtrada","1 colher de chá de sal grosso","1 colher de sopa de açúcar ou mel","1 pitada de bicarbonato de sódio"],preparo:"Dissolva o sal e o açúcar/mel na água. Adicione o bicarbonato. Mexa bem até dissolver completamente.\n\nOfereça nos bebedouros por até 12h, depois troque por água limpa.\n\nUse em dias de calor intenso, após provas longas ou quando o pombo estiver desidratado.\n\n⚠️ Não substitua a água por mais de 12h. Não use em aves com problemas renais sem orientação veterinária."},
  {id:"seed-7",nome:"Soro de Recuperação (2 litros)",categoria:"Eletrólitos",ingredientes:["2 litros de água filtrada","2 colheres de chá de sal grosso","2 colheres de sopa de mel","1 colher de chá de bicarbonato","1 colher de sopa de glicose em pó"],preparo:"Dissolva a glicose e o mel na água morna. Adicione o sal e o bicarbonato. Mexa até dissolver. Deixe esfriar antes de servir.\n\nIdeal para pombos que retornam de provas longas (500km+). Ofereça imediatamente após a chegada.\n\nTroque por água limpa após 8-12h.\n\n⚠️ Não ofereça por mais de 24h consecutivas."},
  {id:"seed-8",nome:"Água com Mel e Limão (1 litro)",categoria:"Respiratório",ingredientes:["1 litro de água filtrada","1 colher de sopa de mel puro","3 gotas de suco de limão"],preparo:"Dissolva o mel na água em temperatura ambiente. Adicione as gotas de limão.\n\nOfereça nos bebedouros por até 8h, depois troque por água limpa.\n\nO mel tem propriedades antibacterianas suaves e o limão é fonte de vitamina C. Use como complemento, não como tratamento.\n\n⚠️ Se houver sinais respiratórios (espirros, secreção), procure veterinário. Não use em aves com candidíase."},
  {id:"seed-9",nome:"Chá de Eucalipto (1 litro)",categoria:"Respiratório",ingredientes:["1 litro de água filtrada","1 colher de sopa de folhas de eucalipto secas"],preparo:"Ferva a água, desligue o fogo e adicione as folhas de eucalipto. Tampe e deixe em infusão por 15 minutos. Coe e espere esfriar.\n\nOfereça nos bebedouros por até 6h, depois troque por água limpa.\n\nUse 1-2 vezes por semana como suporte respiratório. O eucalipto tem propriedades expectorantes.\n\n⚠️ Não substitui tratamento veterinário. Se houver respiração de bico aberto, procure atendimento imediatamente."},
  {id:"seed-10",nome:"Mix Final Velocidade (100g)",categoria:"Pré-prova",ingredientes:["30g açafrão","25g cânhamo","20g girassol descascado","15g linhaça","10g amendoim picado"],preparo:"Misture todas as sementes. Pode adicionar 1 colher de óleo de fígado de bacalhau para aumentar a palatabilidade.\n\nDose: 2g/pombo na quinta-feira (3 dias antes da prova).\n\nDistribua no comedouro à tarde. Não misture na ração — ofereça separado para que todos comam.\n\n⚠️ Não use em aves com digestão lenta ou papo cheio. Não ofereça no dia da prova."},
  {id:"seed-11",nome:"Mix Final Fundo (100g)",categoria:"Pré-prova",ingredientes:["25g açafrão","20g cânhamo","20g amendoim picado","15g girassol descascado","10g linhaça","10g nozes picadas"],preparo:"Mistura de alta energia para provas longas. As nozes e o amendoim fornecem gordura de qualidade.\n\nDose: 3g/pombo conforme protocolo de fundo.\n\nInicie 3 dias antes da prova. Observe se todos os pombos estão comendo.\n\n⚠️ Não enceste aves que não comeram o Mix Final. Não use em aves com problemas hepáticos."},
  {id:"seed-12",nome:"Mistura para Dia Quente (5kg)",categoria:"Personalizada",ingredientes:["2kg milho","1kg trigo","0,5kg sorgo","0,5kg ervilha","0,5kg arroz","0,5kg aveia"],preparo:"Mistura leve e refrescante para dias com temperatura acima de 30°C.\n\nReduza oleaginosas (girassol, amendoim) e aumente grãos leves (arroz, aveia, trigo).\n\nOfereça 25g/pombo/dia. Garanta água limpa e fresca em mais de um ponto. Suspenda treinos nas horas mais quentes.\n\n⚠️ Em calor extremo (>35°C), suspenda treinos e observe sinais de estresse térmico (asas abertas, respiração ofegante)."},
  {id:"seed-13",nome:"Mistura para Dia Frio (5kg)",categoria:"Personalizada",ingredientes:["1,5kg milho","1kg ervilha","1kg girassol","0,5kg amendoim","0,5kg linhaça","0,5kg açafrão"],preparo:"Mistura de alta energia para dias frios (abaixo de 10°C).\n\nAumente as oleaginosas (girassol, amendoim, açafrão) para fornecer mais calorias e gordura.\n\nOfereça 30-35g/pombo/dia. Proteja o pombal de correntes de ar e umidade. Mantenha a água em temperatura ambiente.\n\nObserve perda de peso e ajuste a quantidade conforme condição corporal."},
  {id:"seed-14",nome:"Mistura de Muda de Plumagem (5kg)",categoria:"Recuperação",ingredientes:["1,5kg milho","1kg ervilha","1kg sorgo","0,5kg girassol","0,5kg linhaça","0,5kg açafrão"],preparo:"Durante a muda, o pombo precisa de mais proteína e gordura para formar novas penas.\n\nA ervilha fornece proteína. A linhaça e o açafrão fornecem óleos essenciais para penas brilhantes e resistentes.\n\nOfereça 30g/pombo/dia. Pode adicionar 1 colher de chá de óleo de fígado de bacalhau por kg de mistura.\n\nA muda dura 4-6 semanas. Evite treinos intensos nesse período."},
  {id:"seed-15",nome:"Água com Vinagre de Maçã (1 litro)",categoria:"Eletrólitos",ingredientes:["1 litro de água filtrada","1 colher de sopa de vinagre de maçã natural"],preparo:"Misture o vinagre na água. O pH ácido ajuda a manter o trato digestivo saudável.\n\nOfereça 1-2 vezes por semana nos bebedouros por até 8h.\n\nUse como preventivo, não como tratamento. Não use em aves com problemas gástricos.\n\n⚠️ Não use vinagre comum — apenas vinagre de maçã natural (não filtrado). Não use em dias de prova."},
  {id:"seed-16",nome:"Chá de Camomila (1 litro)",categoria:"Respiratório",ingredientes:["1 litro de água filtrada","2 colheres de sopa de camomila seca"],preparo:"Ferva a água, desligue o fogo e adicione a camomila. Tampe e deixe em infusão por 10 minutos. Coe e espere esfriar.\n\nOfereça nos bebedouros por até 6h.\n\nA camomila tem propriedades calmantes e anti-inflamatórias leves. Use como suporte em situações de estresse (transporte, mudança de ambiente).\n\n⚠️ Não substitui tratamento veterinário."},
];

function vazio():Form{return{nome:"",categoria:"Personalizada",ingredientes:[],preparo:""};}

function carregar():Receita[]{
  try{
    const raw=localStorage.getItem(KEY);
    if(!raw){
      // First time — seed with default recipes
      localStorage.setItem(KEY,JSON.stringify(SEED));
      return SEED;
    }
    const v=JSON.parse(raw);
    return Array.isArray(v)?v:[];
  }catch{return SEED}
}

export default function Receitas(){
  const[receitas,setReceitas]=useState<Receita[]>([]);const[ready,setReady]=useState(false);const[show,setShow]=useState(false);const[cat,setCat]=useState("Todas");const[editId,setEditId]=useState<string|null>(null);const[form,setForm]=useState<Form>(vazio);const[ingrediente,setIngrediente]=useState("");
  useEffect(()=>{setReceitas(carregar());setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(receitas))},[receitas,ready]);
  const filtradas=cat==="Todas"?receitas:receitas.filter(r=>r.categoria===cat);
  function abrir(receita?:Receita){setForm(receita?{nome:receita.nome,categoria:receita.categoria,ingredientes:[...receita.ingredientes],preparo:receita.preparo}:vazio());setEditId(receita?.id||null);setShow(true)}
  function addIngrediente(){const value=ingrediente.trim();if(!value)return;setForm(v=>({...v,ingredientes:[...v.ingredientes,value]}));setIngrediente("")}
  function salvar(){if(!form.nome.trim()){alert("Digite o nome da receita.");return}if(editId)setReceitas(v=>v.map(r=>r.id===editId?{...r,...form}:r));else setReceitas(v=>[...v,{id:crypto.randomUUID(),...form}]);setShow(false);setEditId(null);setForm(vazio())}
  function excluir(id:string){if(confirm("Excluir receita?"))setReceitas(v=>v.filter(r=>r.id!==id))}
  return <main style={{minHeight:"100vh",background:T.bg,color:T.white,padding:"18px 12px 50px"}}><div style={{maxWidth:760,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10,marginBottom:20}}><div><Link href="/centro-provas" style={{...T.small,textDecoration:"none"}}>← Centro de Provas</Link><h1 style={{...T.h1,marginTop:9}}>🧪 Receitas Caseiras</h1><p style={{...T.small,marginTop:4}}>Preparações e misturas personalizadas do plantel</p></div><button onClick={()=>abrir()} style={T.btnSm}>+ Nova</button></div>
    <div style={{padding:"10px 13px",marginBottom:13,borderRadius:9,color:T.blue,background:`${T.blue}12`,border:`1px solid ${T.blue}44`,fontSize:11,lineHeight:1.6}}>ℹ️ Registre apenas ingredientes seguros para aves. Receitas não substituem tratamento, diagnóstico ou produto veterinário. Valide doses e compatibilidade com profissional especializado.</div>
    <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:14}}>{["Todas",...CATS].map(c=><button key={c} onClick={()=>setCat(c)} style={{padding:"7px 13px",borderRadius:20,fontSize:12,fontWeight:700,color:cat===c?T.bg:T.dim,background:cat===c?T.gold:T.bgCard,border:`1px solid ${cat===c?T.gold:T.border}`}}>{c}</button>)}</div>
    {show&&<section style={T.card}><Title>{editId?"✏️ Editar Receita":"➕ Nova Receita"}</Title><Field label="Nome *"><input value={form.nome} onChange={e=>setForm(v=>({...v,nome:e.target.value}))} placeholder="Nome da receita" style={T.input}/></Field><Field label="Categoria"><select value={form.categoria} onChange={e=>setForm(v=>({...v,categoria:e.target.value}))} style={T.input}>{CATS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Ingredientes"><div style={{display:"flex",gap:6}}><input value={ingrediente} onChange={e=>setIngrediente(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addIngrediente()}}} placeholder="Ingrediente e quantidade..." style={{...T.input,flex:1}}/><button onClick={addIngrediente} style={T.btnSm}>+</button></div><div style={{display:"flex",flexWrap:"wrap",gap:5,marginTop:7}}>{form.ingredientes.map((item,i)=><span key={`${item}-${i}`} style={{display:"flex",alignItems:"center",gap:5,padding:"3px 9px",borderRadius:20,color:T.gold,background:`${T.gold}18`,fontSize:11}}>{item}<button onClick={()=>setForm(v=>({...v,ingredientes:v.ingredientes.filter((_,j)=>j!==i)}))} style={{padding:0,color:T.gold,background:"none",border:0}}>×</button></span>)}</div></Field><Field label="Modo de preparo e uso"><textarea rows={4} value={form.preparo} onChange={e=>setForm(v=>({...v,preparo:e.target.value}))} placeholder="Como preparar, quantidade e quando oferecer..." style={{...T.input,height:100}}/></Field><div style={{display:"flex",gap:8}}><button onClick={()=>{setShow(false);setEditId(null)}} style={{...T.btnGhost,flex:1}}>Cancelar</button><button onClick={salvar} style={{...T.btn,flex:2}}>💾 Salvar</button></div></section>}
    <div style={{display:"grid",gap:10}}>{filtradas.map(r=>{const cor=CORES[r.categoria]||T.gold;return <section key={r.id} style={T.card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:10}}><div style={{display:"flex",gap:10}}><span style={{width:40,height:40,display:"grid",placeItems:"center",borderRadius:10,fontSize:20,background:`${cor}20`,border:`2px solid ${cor}44`}}>🧪</span><div><b>{r.nome}</b><div><small style={{padding:"2px 7px",borderRadius:20,color:cor,background:`${cor}18`}}>{r.categoria}</small></div></div></div><div style={{display:"flex",gap:5}}><button onClick={()=>abrir(r)} style={T.btnGhost}>✏️</button><button onClick={()=>excluir(r.id)} style={T.btnDanger}>🗑️</button></div></div><div style={{display:"flex",flexWrap:"wrap",gap:5,margin:"11px 0"}}>{r.ingredientes.map((item,i)=><span key={`${item}-${i}`} style={{padding:"3px 9px",borderRadius:20,color:cor,background:`${cor}15`,fontSize:11}}>{item}</span>)}</div>{r.preparo&&<div style={{paddingTop:9,borderTop:`1px solid ${T.border}`,color:T.dim,fontSize:13,whiteSpace:"pre-wrap"}}>{r.preparo}</div>}</section>})}{ready&&!filtradas.length&&<div style={{textAlign:"center",padding:32,color:T.dim}}>Nenhuma receita encontrada.</div>}</div>
  </div><style jsx global>{`button,input,select,textarea{font-family:inherit}button{cursor:pointer}select option{background:${T.bgInput}}`}</style></main>
}
function Title({children}:{children:React.ReactNode}){return <div style={{fontSize:13,fontWeight:800,color:T.gold,marginBottom:11}}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:"block",marginBottom:12}}><span style={{...T.label,display:"block",marginBottom:5}}>{label}</span>{children}</label>}
